"""HLD MCQs — Caching, Sharding, Consistent Hashing, CAP Theorem, Numbers to Know."""
from __future__ import annotations
from .lld_practice import quiz, Lesson


def caching_lesson() -> Lesson:
    return Lesson(
        id="hld-caching", number=103, title="Caching Deep Dive",
        focus=("cache strategies", "eviction", "invalidation", "Redis", "CDN"),
        overview="Caching is the most common performance optimization in system design. Master the strategies and pitfalls.",
        patterns=(), badge="HLD",
        tasks=(
            quiz("cache-1", "What is the difference between cache-aside and write-through caching?",
                 "medium", ("caching",),
                 ("No difference", "Cache-aside: app reads/writes cache on demand. Write-through: writes go to cache and DB simultaneously", "Write-through is slower", "Cache-aside doesn't use a cache"), 1,
                 "Cache-aside (lazy loading) fills cache on miss. Write-through ensures cache is always up-to-date but adds write latency."),
            quiz("cache-2", "What is write-behind (write-back) caching?",
                 "hard", ("caching",),
                 ("Same as write-through", "Writes go to cache first, then asynchronously flushed to DB in batches", "Writes skip the cache", "A read-only strategy"), 1,
                 "Write-behind improves write performance but risks data loss if the cache crashes before flushing."),
            quiz("cache-3", "What is cache stampede (thundering herd on cache miss)?",
                 "hard", ("caching", "scaling"),
                 ("Cache overflow", "Many requests simultaneously miss the cache and hit the database, causing overload", "A cache eviction policy", "A CDN failure"), 1,
                 "Mitigations: locking (only one fetcher), request coalescing, or pre-warming the cache before TTL expiry."),
            quiz("cache-4", "What is the difference between LRU and LFU eviction?",
                 "medium", ("caching", "eviction"),
                 ("They are the same", "LRU evicts least recently used; LFU evicts least frequently used", "LFU is always better", "LRU uses more memory"), 1,
                 "LRU works well for temporal locality. LFU favors popular items but can be slow to adapt to changing access patterns."),
            quiz("cache-5", "When is TTL-based cache invalidation appropriate?",
                 "medium", ("caching", "invalidation"),
                 ("Never", "When eventual consistency is acceptable and the data changes predictably", "Only for images", "When data never changes"), 1,
                 "TTL is simple but data can be stale up to the TTL duration. Good for config, search results, and non-critical data."),
            quiz("cache-6", "What is cache warming and why would you do it?",
                 "medium", ("caching",),
                 ("Resetting the cache", "Pre-loading frequently accessed data into cache before traffic arrives", "A type of eviction", "Encrypting cached data"), 1,
                 "Cache warming prevents cold-start latency spikes after deployments or cache node replacements."),
            quiz("cache-7", "What is the difference between a local cache and a distributed cache?",
                 "medium", ("caching", "architecture"),
                 ("Local is always faster", "Local is per-instance (in-memory); distributed is shared across instances (Redis, Memcached)", "Distributed can't use Redis", "Local is more consistent"), 1,
                 "Local caches (HashMap) are fastest but inconsistent across instances. Distributed caches ensure shared state."),
            quiz("cache-8", "What problem does cache invalidation solve and why is it hard?",
                 "hard", ("caching", "invalidation"),
                 ("Performance optimization", "Keeping cache in sync with the source of truth — hard because of race conditions, distributed systems, and timing", "Data encryption", "Load balancing"), 1,
                 "'There are only two hard things in CS: cache invalidation and naming things.' — Phil Karlton"),
            quiz("cache-9", "In Redis, what is the difference between a String and a Hash data structure?",
                 "hard", ("caching", "redis"),
                 ("No difference", "String stores a single value per key; Hash stores a map of field-value pairs under one key", "Hash is slower", "String can store objects"), 1,
                 "Redis Hash is ideal for storing object fields (user:123 → {name, email, age}) without serializing the whole object."),
            quiz("cache-10", "What is a cache-aside read flow?",
                 "easy", ("caching",),
                 ("Always read from DB", "Check cache → if miss, read from DB → write result to cache → return", "Write to cache first, then read", "Read from CDN only"), 1,
                 "Cache-aside is the most common pattern. The application manages the cache explicitly."),
            quiz("cache-11", "What is Redis pub/sub and when would you use it?",
                 "medium", ("caching", "redis"),
                 ("A database transaction", "A messaging system where publishers send messages to channels and subscribers receive them in real-time", "A cache eviction policy", "A replication mode"), 1,
                 "Redis pub/sub is lightweight real-time messaging — useful for chat, notifications, cache invalidation broadcasts."),
            quiz("cache-12", "What are the risks of caching sensitive data like user sessions?",
                 "medium", ("caching", "security"),
                 ("No risks", "Data leaks if cache is compromised; stale sessions if cache evicts before session expires", "Caching is always secure", "It's only a performance risk"), 1,
                 "Sensitive cached data needs encryption, proper TTLs, and secure network access controls."),
            quiz("cache-13", "What is the difference between Memcached and Redis?",
                 "medium", ("caching",),
                 ("They are identical", "Redis supports data structures (lists, sets, hashes), persistence, and replication; Memcached is simpler key-value only", "Memcached is newer", "Redis can't cluster"), 1,
                 "Redis is more feature-rich (pub/sub, Lua scripts, persistence). Memcached is simpler and can be faster for pure KV workloads."),
            quiz("cache-14", "What is a read-through cache?",
                 "medium", ("caching",),
                 ("Same as cache-aside", "The cache itself is responsible for loading data from the DB on a miss, transparent to the app", "A write-only cache", "A CDN feature"), 1,
                 "Read-through differs from cache-aside: the cache library handles DB fetching, not the application code."),
            quiz("cache-15", "What is cache penetration?",
                 "hard", ("caching",),
                 ("Cache overflow", "Requests for data that doesn't exist bypass cache and always hit the DB", "A security attack", "Cache eviction"), 1,
                 "Mitigations: cache negative results with short TTL, or use a Bloom filter to check existence before querying."),
            quiz("cache-16", "What is the 80/20 rule in caching?",
                 "easy", ("caching",),
                 ("Cache 80% of data", "~80% of requests hit ~20% of data, so caching the hot 20% handles most traffic", "Use 80% cache hit rate", "Evict after 80 seconds"), 1,
                 "Pareto principle: a small subset of data serves most requests, making caching highly effective."),
            quiz("cache-17", "What is Redis Cluster and how does it shard data?",
                 "hard", ("caching", "redis"),
                 ("It doesn't shard", "Distributes data across multiple nodes using hash slots (16384 slots mapped to nodes)", "Uses consistent hashing only", "Shards by key prefix"), 1,
                 "Redis Cluster assigns each key to one of 16384 hash slots, which are distributed across master nodes."),
            quiz("cache-18", "What is a cache coherence problem in multi-level caching?",
                 "hard", ("caching",),
                 ("Cache is too small", "Different cache levels (L1/L2/CDN/app) may have different versions of the same data", "Cache is too slow", "A CDN issue only"), 1,
                 "Multi-level caches need coordinated invalidation or versioned keys to maintain consistency."),
            quiz("cache-19", "What is a Bloom filter and how does it relate to caching?",
                 "hard", ("caching", "data-structures"),
                 ("A cache eviction policy", "A probabilistic data structure that can tell if a key definitely doesn't exist or might exist, preventing unnecessary lookups", "A sorting algorithm", "A hash function"), 1,
                 "Bloom filters prevent cache penetration: if the filter says 'no', the key definitely doesn't exist in DB."),
            quiz("cache-20", "When should you NOT use caching?",
                 "medium", ("caching", "tradeoffs"),
                 ("Never, always cache", "When data changes very frequently, consistency is critical, or the working set is too large to fit in memory", "When using NoSQL", "When using CDNs"), 1,
                 "Caching adds complexity. Skip it for rapidly changing data, strongly consistent requirements, or rarely accessed data."),
        ),
    )


def sharding_lesson() -> Lesson:
    return Lesson(
        id="hld-sharding", number=104, title="Sharding & Partitioning",
        focus=("shard keys", "strategies", "rebalancing", "hotspots"),
        overview="Sharding is how you scale databases horizontally. The shard key choice makes or breaks the design.",
        patterns=(), badge="HLD",
        tasks=(
            quiz("shard-1", "What is database sharding?",
                 "easy", ("sharding",),
                 ("Backing up data", "Splitting a database across multiple machines, each holding a subset of the data", "Replicating data", "Indexing tables"), 1,
                 "Sharding distributes rows across nodes so no single machine handles all traffic."),
            quiz("shard-2", "What makes a good shard key?",
                 "hard", ("sharding",),
                 ("The primary key always", "High cardinality, even distribution, frequently used in queries, and rarely changing", "Any random column", "The timestamp column"), 1,
                 "A good shard key distributes data evenly and supports the most common query patterns."),
            quiz("shard-3", "What is a hot shard and how do you fix it?",
                 "hard", ("sharding",),
                 ("A shard with latest data", "A shard receiving disproportionate traffic due to poor key distribution — fix by choosing a better key or adding salting", "A shard that's full", "A replica that's slow"), 1,
                 "Hot shards occur when a key value is too popular. Solutions: composite keys, salting, or range-based splitting."),
            quiz("shard-4", "What is the difference between range-based and hash-based sharding?",
                 "medium", ("sharding",),
                 ("They are identical", "Range assigns key ranges to shards (good for scans); hash assigns by hash value (good for distribution)", "Hash is always better", "Range doesn't work with strings"), 1,
                 "Range sharding supports range queries but risks hotspots. Hash sharding distributes evenly but makes range queries expensive."),
            quiz("shard-5", "What is a cross-shard query and why is it expensive?",
                 "hard", ("sharding",),
                 ("A query on a single shard", "A query that needs data from multiple shards, requiring scatter-gather and coordination", "A backup query", "A cached query"), 1,
                 "Cross-shard queries are slow because they fan out to multiple nodes and require merging results."),
            quiz("shard-6", "What is shard rebalancing?",
                 "medium", ("sharding",),
                 ("Deleting old data", "Moving data between shards when load becomes uneven or shards are added/removed", "Creating replicas", "Backing up shards"), 1,
                 "Rebalancing redistributes data — it's expensive and must be done carefully to avoid downtime."),
            quiz("shard-7", "Why is consistent hashing useful for sharding?",
                 "hard", ("sharding", "consistent-hashing"),
                 ("It encrypts the shard key", "When a node is added/removed, only a small fraction of keys need to be remapped", "It sorts data", "It prevents hotspots completely"), 1,
                 "Consistent hashing minimizes key redistribution during cluster changes, unlike modulo hashing which remaps almost everything."),
            quiz("shard-8", "What is the problem with using auto-increment IDs as shard keys?",
                 "hard", ("sharding",),
                 ("They are too long", "Sequential IDs route all new writes to the same shard, creating a hotspot", "They are not unique", "They use too much memory"), 1,
                 "Sequential keys concentrate recent writes on one shard. Use UUIDs, snowflake IDs, or hash-based assignment instead."),
            quiz("shard-9", "What is a lookup/directory-based sharding approach?",
                 "medium", ("sharding",),
                 ("Sharding by file name", "A central service maps each key to its shard, allowing flexible placement at the cost of an extra hop", "A hash function", "A replication strategy"), 1,
                 "Directory-based sharding (e.g., metadata DB) offers maximum flexibility but the directory becomes a SPOF."),
            quiz("shard-10", "How does sharding affect JOIN operations?",
                 "hard", ("sharding",),
                 ("No effect", "JOINs across shards become very expensive or impossible — denormalize or co-locate related data", "JOINs become faster", "Sharding enables new JOIN types"), 1,
                 "This is a fundamental tradeoff: sharding sacrifices JOIN capability. Design around it by co-locating or denormalizing."),
            quiz("shard-11", "What is geo-sharding?",
                 "medium", ("sharding",),
                 ("Sharding by data type", "Partitioning data by geographic region so users' data is stored near them", "A CDN feature", "Sharding by timestamp"), 1,
                 "Geo-sharding reduces latency and can help with data residency regulations (GDPR)."),
            quiz("shard-12", "What is a scatter-gather query pattern?",
                 "hard", ("sharding",),
                 ("A caching pattern", "Send the query to all shards (scatter), collect results, merge and return (gather)", "A replication pattern", "A load balancing technique"), 1,
                 "Scatter-gather is necessary when the shard key isn't in the query. It's expensive but sometimes unavoidable."),
            quiz("shard-13", "What is the difference between sharding and partitioning?",
                 "medium", ("sharding",),
                 ("They are completely different", "Partitioning is the general concept; sharding specifically refers to distributing partitions across different machines", "Sharding is for NoSQL only", "Partitioning is for reads, sharding for writes"), 1,
                 "A single PostgreSQL can have partitions (within one machine). Sharding distributes those partitions across nodes."),
            quiz("shard-14", "What is virtual sharding / virtual nodes?",
                 "hard", ("sharding", "consistent-hashing"),
                 ("Sharding in the cloud", "Each physical node owns multiple virtual positions on the hash ring for better load distribution", "A simulation technique", "Sharding without a database"), 1,
                 "Virtual nodes (vnodes) improve balance in consistent hashing by giving each physical node multiple points on the ring."),
            quiz("shard-15", "What is the challenge of maintaining unique constraints across shards?",
                 "hard", ("sharding",),
                 ("No challenge", "Each shard only sees its own data, so global uniqueness requires a centralized check or clever key design", "Unique constraints are automatic", "Shards share indexes"), 1,
                 "Options: global unique ID generator (Snowflake), centralized uniqueness service, or design keys to be inherently unique."),
            quiz("shard-16", "How does Instagram generate unique IDs for sharded data?",
                 "hard", ("sharding", "design"),
                 ("Auto-increment per shard", "A Snowflake-like approach: timestamp + shard ID + sequence number", "UUIDs", "Random numbers"), 1,
                 "Instagram's ID format: 41 bits timestamp + 13 bits shard ID + 10 bits sequence = unique, sortable, shard-aware."),
            quiz("shard-17", "What is data co-location in sharding?",
                 "medium", ("sharding",),
                 ("Storing all data on one server", "Placing related data on the same shard to enable efficient local JOINs and transactions", "A backup strategy", "A CDN technique"), 1,
                 "Co-location avoids cross-shard operations. Example: shard by user_id so all of a user's data is on one shard."),
            quiz("shard-18", "What happens to transactions in a sharded database?",
                 "hard", ("sharding",),
                 ("They work the same", "Single-shard transactions work normally; cross-shard transactions require 2PC or Saga patterns", "Transactions are not supported", "They become faster"), 1,
                 "Cross-shard transactions are expensive (2PC) or must be redesigned as eventual consistency workflows (Sagas)."),
            quiz("shard-19", "What is resharding and why is it painful?",
                 "hard", ("sharding",),
                 ("Adding indexes", "Changing the sharding scheme requires moving data between shards with zero or minimal downtime", "Removing shards", "Adding replicas"), 1,
                 "Resharding involves massive data migration, potential inconsistency, and complex coordination. Plan your shard key carefully upfront."),
            quiz("shard-20", "For a social network, why is sharding by user_id generally better than sharding by post_id?",
                 "hard", ("sharding", "design"),
                 ("User IDs are smaller", "Most queries are user-centric (my feed, my posts) so co-locating a user's data avoids cross-shard queries", "Post IDs have hotspots", "User IDs are sequential"), 1,
                 "User-centric access patterns dominate social networks. Sharding by user_id keeps most operations local to one shard."),
        ),
    )


def cap_and_numbers_lesson() -> Lesson:
    return Lesson(
        id="hld-cap-numbers", number=105, title="CAP Theorem & Numbers to Know",
        focus=("CAP", "PACELC", "latency numbers", "throughput estimates", "back-of-envelope"),
        overview="CAP theorem drives database selection. The numbers let you estimate capacity and justify design choices.",
        patterns=(), badge="HLD",
        tasks=(
            quiz("cap-1", "What does CAP theorem actually state?",
                 "medium", ("cap",),
                 ("You can have all three", "During a network partition, you must choose between Consistency and Availability", "It's about CPU, Availability, and Performance", "It only applies to SQL databases"), 1,
                 "CAP: when a partition occurs (P is guaranteed in distributed systems), you choose CP or AP."),
            quiz("cap-2", "Is DynamoDB CP or AP?",
                 "hard", ("cap",),
                 ("CP", "AP by default (eventually consistent reads), with optional strongly consistent reads", "Neither", "Both"), 1,
                 "DynamoDB defaults to eventually consistent reads (AP) but offers strongly consistent reads at higher latency/cost."),
            quiz("cap-3", "Is PostgreSQL CP or AP?",
                 "medium", ("cap",),
                 ("AP", "CP — it prioritizes consistency over availability during partitions", "Neither", "Depends on version"), 1,
                 "Traditional RDBMS like PostgreSQL are CP: they reject writes rather than risk inconsistency."),
            quiz("cap-4", "What does PACELC theorem add to CAP?",
                 "hard", ("cap",),
                 ("Nothing, same thing", "When there's no partition (E for Else), you still choose between Latency and Consistency", "It replaces CAP", "It adds Performance"), 1,
                 "PACELC: if Partition → choose A or C. Else → choose L(atency) or C(onsistency). More nuanced than CAP."),
            quiz("cap-5", "How many bytes in a typical UUID?",
                 "medium", ("numbers",),
                 ("4 bytes", "8 bytes", "16 bytes", "32 bytes"), 2,
                 "A UUID is 128 bits = 16 bytes. As a hex string with dashes: 36 characters."),
            quiz("cap-6", "What is the approximate latency of a round-trip within the same data center?",
                 "medium", ("numbers",),
                 ("1 ns", "0.5 ms", "50 ms", "500 ms"), 1,
                 "Intra-datacenter round-trip is ~0.5ms. Cross-continent is ~100-150ms."),
            quiz("cap-7", "How many QPS can a single modern server typically handle for simple API requests?",
                 "medium", ("numbers",),
                 ("100 QPS", "1,000 QPS", "10,000-50,000 QPS", "1 million QPS"), 2,
                 "A well-optimized single server can handle 10K-50K simple API requests/sec. Complex queries reduce this."),
            quiz("cap-8", "What is the approximate sequential read speed of an SSD?",
                 "medium", ("numbers",),
                 ("1 MB/s", "50 MB/s", "500 MB/s - 1 GB/s", "10 GB/s"), 2,
                 "Modern NVMe SSDs read sequentially at 500MB/s to 3GB/s. Random reads are slower."),
            quiz("cap-9", "How much data can a single PostgreSQL instance typically handle well?",
                 "hard", ("numbers",),
                 ("1 GB", "A few hundred GB to low TB range", "100 TB", "1 PB"), 1,
                 "PostgreSQL performs well up to a few hundred GB to low terabytes. Beyond that, consider sharding or a distributed DB."),
            quiz("cap-10", "What is the quorum formula for N replicas?",
                 "hard", ("cap", "consistency"),
                 ("N/2", "W + R > N, where W is write quorum and R is read quorum", "N - 1", "Always N"), 1,
                 "Quorum ensures overlap between write and read sets. For N=3: W=2, R=2 guarantees reading latest write."),
            quiz("cap-11", "If a system has 1 billion users and each user record is 1 KB, how much storage is needed?",
                 "easy", ("numbers",),
                 ("1 GB", "100 GB", "1 TB", "1 PB"), 2,
                 "1 billion × 1 KB = 1 TB. This is a common back-of-envelope calculation in interviews."),
            quiz("cap-12", "What is the approximate latency of reading 1 MB from memory?",
                 "hard", ("numbers",),
                 ("1 ns", "250 μs (0.25 ms)", "10 ms", "100 ms"), 1,
                 "Sequential memory read: ~250μs for 1MB. Compare: SSD ~1ms, HDD ~20ms for same."),
            quiz("cap-13", "What is the two-generals problem?",
                 "hard", ("cap", "distributed"),
                 ("A scheduling problem", "It's impossible to guarantee agreement between two parties over an unreliable network", "A load balancing issue", "A caching problem"), 1,
                 "The two-generals problem proves that consensus over unreliable networks is impossible — foundational to distributed systems."),
            quiz("cap-14", "What is split-brain in distributed systems?",
                 "hard", ("cap",),
                 ("A database error", "When a partition causes two halves of a cluster to each believe they are the leader, leading to conflicting writes", "A caching issue", "A load balancer failure"), 1,
                 "Split-brain can cause data corruption. Solutions: quorum-based leader election, fencing tokens, STONITH."),
            quiz("cap-15", "If a service handles 10K requests/sec and each request takes 100ms, how many concurrent connections are needed?",
                 "medium", ("numbers",),
                 ("100", "1,000", "10,000", "100,000"), 1,
                 "Concurrency = Throughput × Latency = 10,000 × 0.1s = 1,000 concurrent connections (Little's Law)."),
            quiz("cap-16", "What is the approximate cost difference between RAM and SSD per GB?",
                 "medium", ("numbers",),
                 ("Same cost", "RAM is ~30-50x more expensive per GB than SSD", "SSD is more expensive", "RAM is 2x more expensive"), 1,
                 "RAM: ~$5-10/GB. SSD: ~$0.10-0.25/GB. This drives caching and storage tier decisions."),
            quiz("cap-17", "What is a vector clock?",
                 "hard", ("cap", "distributed"),
                 ("A physical clock synced via NTP", "A logical clock that tracks causality across nodes using per-node counters, detecting concurrent events", "A timestamp format", "A load balancing algorithm"), 1,
                 "Vector clocks enable detecting causality and concurrency in distributed systems without synchronized clocks."),
            quiz("cap-18", "What is Cassandra's consistency model?",
                 "hard", ("cap",),
                 ("Always strongly consistent", "Tunable consistency — you choose consistency level per query (ONE, QUORUM, ALL)", "Eventually consistent only", "Same as PostgreSQL"), 1,
                 "Cassandra lets you choose consistency per operation: ONE (fast, potentially stale) to ALL (slow, consistent)."),
            quiz("cap-19", "How many bytes per second does a 1 Gbps network link provide?",
                 "medium", ("numbers",),
                 ("1 GB/s", "~125 MB/s", "1 MB/s", "10 GB/s"), 1,
                 "1 Gbps = 1,000,000,000 bits/sec ÷ 8 = 125 MB/s. Real throughput is slightly less due to overhead."),
            quiz("cap-20", "What does the '5 nines' (99.999%) availability translate to in annual downtime?",
                 "medium", ("numbers",),
                 ("~5 minutes/year", "~5 hours/year", "~1 hour/year", "~52 minutes/year"), 0,
                 "99.999% = 5.26 min/year. 99.99% = 52.6 min/year. 99.9% = 8.76 hours/year."),
        ),
    )
