"""HLD Core Concepts: Database Indexing, Caching — 20 MCQs each."""
from __future__ import annotations
from .lld_practice import quiz, Lesson

def db_indexing_lesson() -> Lesson:
    return Lesson(id="hld-db-indexing", number=103, title="Database Indexing",
        focus=("B-tree","hash index","composite","covering","LSM tree","bitmap"),
        overview="Indexing is the most impactful DB optimization. Know internals, tradeoffs, and when NOT to index.",
        patterns=(), badge="HLD Core", tasks=(
        quiz("idx-1","What is a B-tree index and why is it the default?","hard",("indexing",),("A binary search tree stored entirely in memory for O(1) lookups on any key","A hash-based structure that only supports exact-match queries efficiently","A balanced tree keeping data sorted for O(log n) lookups, range queries, and ordered scans","An append-only log structure that batches writes for sequential I/O throughput"),2,"B-trees are the backbone of relational DB indexes — equality, range, and prefix queries."),
        quiz("idx-2","When would you choose a hash index over a B-tree?","hard",("indexing",),("When you need range queries and ORDER BY on the indexed column","Only exact-match lookups needed, wanting O(1) average performance","When the column has very low cardinality and many duplicate values","When you need prefix matching and LIKE queries on text columns"),1,"Hash indexes are O(1) for point lookups but can't support range, ORDER BY, or prefix matching."),
        quiz("idx-3","What is a composite index?","medium",("indexing",),("An index that automatically spans all columns in the table schema","A unique constraint applied to multiple columns simultaneously","An index on multiple columns, useful when queries filter on combinations","A foreign key constraint that creates indexes on both referenced tables"),2,"Composite indexes follow the leftmost prefix rule: index on (a,b,c) supports (a), (a,b), (a,b,c)."),
        quiz("idx-4","What is a covering index?","hard",("indexing",),("An index that covers all tables in a database for cross-table queries","A backup index that takes over when the primary index becomes corrupted","An index on the primary key column that is automatically created by the DB","An index containing all columns needed by a query, eliminating table lookups"),3,"Covering indexes avoid table lookups entirely, significantly improving read performance."),
        quiz("idx-5","What is the leftmost prefix rule for composite indexes?","hard",("indexing",),("You must always use the leftmost table in a JOIN for the optimizer to use indexes","Index on (a,b,c) can serve queries on (a), (a,b), (a,b,c) but NOT (b,c) alone","Always place the column with the lowest cardinality leftmost in the index definition","The leftmost column is always used for sorting regardless of the query ORDER BY"),1,"The index can be used as long as the query filters start from the leftmost column."),
        quiz("idx-6","What is an LSM tree and which databases use it?","hard",("indexing",),("A B-tree variant used by PostgreSQL for its default BTREE index type","A read-optimized tree structure used by Oracle for OLAP analytical workloads","A write-optimized structure using memtable+SSTables with compaction — used by Cassandra, RocksDB","An in-memory hash table used by Redis for its sorted set implementation"),2,"LSM trees batch writes in memory, flush to sorted files, then compact. Much faster writes than B-trees."),
        quiz("idx-7","What is the difference between a clustered and non-clustered index?","hard",("indexing",),("Clustered indexes are distributed across multiple nodes; non-clustered are local","Non-clustered indexes are always faster because they avoid locking table data","Clustered sorts the actual table data (one per table); non-clustered is a separate structure pointing to rows","Clustered indexes only work with primary keys; non-clustered work with any column"),2,"A clustered index determines physical row order. A table can have only one clustered index (usually PK)."),
        quiz("idx-8","What is index selectivity and why does it matter?","hard",("indexing",),("How quickly the database can build an index during CREATE INDEX operations","The ratio of distinct values to total rows — higher selectivity means the index is more useful","The amount of physical memory the index consumes relative to the table data","How many concurrent queries can use the same index without lock contention"),1,"An index on a boolean column (selectivity ~50%) is nearly useless. An index on email (high selectivity) is very useful."),
        quiz("idx-9","When should you NOT create an index?","medium",("indexing",),("When using NoSQL databases, since they don't support secondary indexes at all","When the table has more than 1 million rows and query latency is critical","When the table is small, column has low cardinality, or writes vastly outnumber reads","When the column is used in WHERE clauses of frequently executed queries"),2,"Indexes speed reads but slow writes (each INSERT/UPDATE must maintain the index)."),
        quiz("idx-10","What is a partial (filtered) index?","hard",("indexing",),("An incomplete index that was interrupted during creation and needs rebuilding","An index on only the first few characters of a text column to save space","An index that only covers rows matching a WHERE condition, saving space and improving performance","A temporary index created during query execution and dropped immediately after"),2,"Example: CREATE INDEX ON orders(status) WHERE status='pending' — only indexes pending orders."),
        quiz("idx-11","What is a bitmap index and when is it useful?","hard",("indexing",),("An index stored as a compressed image file for visual query plan representation","A B-tree variant that stores bitmaps instead of pointers for faster range queries","Uses bitmaps for each distinct value — efficient for low-cardinality columns in analytics","A full-text search index that maps words to their positions in each document"),2,"Bitmap indexes excel at combining filters (AND/OR) on low-cardinality columns (gender, status, region)."),
        quiz("idx-12","What is EXPLAIN/EXPLAIN ANALYZE used for?","medium",("indexing",),("Creating indexes automatically based on query workload analysis by the optimizer","Showing the query execution plan — which indexes are used, scan types, estimated costs","Deleting unused indexes that haven't been accessed within a configurable time window","Optimizing write performance by suggesting batch sizes and commit intervals"),1,"EXPLAIN reveals if your query uses an index, does a full table scan, or picks the wrong plan."),
        quiz("idx-13","What is a full table scan and when is it acceptable?","medium",("indexing",),("Never acceptable in production; it always indicates a missing index or bad query","Only acceptable when the database is hosted on SSD storage with low I/O latency","Reading every row — acceptable for small tables or queries returning a large percentage of rows","Always the fastest scan type because it reads data sequentially without index overhead"),2,"The optimizer may choose a full scan over an index when >20-30% of rows match."),
        quiz("idx-14","What is an inverted index?","hard",("indexing",),("A B-tree stored in reverse key order for descending range queries","A hash table where values point back to their keys for reverse lookups","Maps each unique term to the list of documents containing it — used for full-text search","A sorted array of row IDs used for bitmap operations in analytics queries"),2,"Elasticsearch and Lucene use inverted indexes: term → [doc1, doc5, doc42] for O(1) term lookups."),
        quiz("idx-15","What is index bloat and how do you fix it?","hard",("indexing",),("When too many indexes are created on a table, slowing down the query optimizer","Having excessively wide composite indexes that waste memory on unused columns","When dead tuples inflate index size due to UPDATE/DELETE without VACUUM — fix with REINDEX","Index corruption from hardware failures requiring a full database restore from backup"),2,"In PostgreSQL, MVCC creates dead tuples. Without regular VACUUM, indexes grow unnecessarily."),
        quiz("idx-16","What is the write amplification problem with indexes?","hard",("indexing",),("Writes become too small and waste I/O bandwidth on partially filled disk pages","Each write to the table requires updating every index on that table, multiplying write I/O","Write operations are duplicated across replicas, doubling the total disk usage","A network issue where write acknowledgments are sent multiple times due to retries"),1,"A table with 5 indexes means each INSERT does 6 writes (1 table + 5 indexes)."),
        quiz("idx-17","What is a GIN index and when would you use it?","hard",("indexing",),("A B-tree variant optimized for text columns in PostgreSQL 15 and later","A hash index with built-in collision resolution for high-cardinality columns","A bitmap index type used exclusively for boolean and enum columns","Generalized Inverted Index — for full-text search, JSONB queries, and array containment in PostgreSQL"),3,"GIN indexes handle composite values: full-text search (tsvector), JSONB paths, and array @> operators."),
        quiz("idx-18","What is the difference between a unique index and a unique constraint?","medium",("indexing",),("Unique index is much faster because it skips constraint validation on each insert","A unique constraint doesn't create any index; it relies on table scans for enforcement","Functionally identical in most DBs — unique constraint is declarative, unique index is implementation","Unique indexes allow NULL values; unique constraints reject NULLs in all cases"),2,"In PostgreSQL, a UNIQUE constraint automatically creates a unique index under the hood."),
        quiz("idx-19","How does indexing affect JOIN performance?","hard",("indexing",),("Indexes have no effect on JOINs; only the join algorithm (nested loop vs hash) matters","JOINs cannot use indexes and always require full table scans on both sides","Only the first table in the JOIN clause benefits from indexes; subsequent tables are scanned","Indexes on JOIN columns allow index nested loop joins instead of full scans, dramatically improving performance"),3,"Index the foreign key columns. Without indexes, JOINs may degrade to O(n×m) nested loop scans."),
        quiz("idx-20","What is an adaptive hash index in InnoDB?","hard",("indexing",),("A manually created hash index that the DBA configures for specific workloads","A B-tree optimization that pre-sorts leaf pages for faster sequential range scans","A query cache that stores the results of frequently executed SELECT statements","An automatic in-memory hash index built by InnoDB for frequently accessed B-tree pages"),3,"InnoDB monitors access patterns and automatically builds hash indexes for hot pages, giving O(1) lookups."),
    ))

def caching_lesson() -> Lesson:
    return Lesson(id="hld-caching", number=104, title="Caching",
        focus=("cache-aside","write-through","eviction","Redis","CDN","invalidation"),
        overview="Caching is the #1 performance optimization. Master strategies, pitfalls, and Redis internals.",
        patterns=(), badge="HLD Core", tasks=(
        quiz("cache-1","What is cache-aside (lazy loading)?","medium",("caching",),("Write to cache first, then asynchronously persist to DB in batches","Always read directly from DB and populate cache on every response","Check cache → if miss, read from DB → write to cache → return","Pre-load the entire dataset into cache on application startup"),2,"Cache-aside is the most common pattern. The application manages the cache explicitly."),
        quiz("cache-2","What is write-through caching?","medium",("caching",),("Same as cache-aside but with automatic TTL-based expiration on writes","Writes go to cache AND DB simultaneously, keeping cache always up-to-date","Writes go only to DB; cache is populated lazily on the next read miss","A read-only caching strategy where the cache is never written to directly"),1,"Write-through ensures cache freshness but adds write latency."),
        quiz("cache-3","What is write-behind (write-back) caching?","hard",("caching",),("Same as write-through but with synchronous replication to standby caches","Writes go to cache first, then asynchronously flushed to DB in batches","Writing to both cache and DB simultaneously with a two-phase commit protocol","A read-only strategy where changes bypass cache and go directly to the database"),1,"Write-behind improves write performance but risks data loss if cache crashes before flushing."),
        quiz("cache-4","What is cache stampede?","hard",("caching",),("Cache memory overflow causing the eviction policy to remove all hot entries","An eviction policy where the oldest entries are removed regardless of access frequency","A CDN failure where all edge nodes simultaneously purge their cached content","Many requests simultaneously miss the cache and hit the DB, causing overload"),3,"Mitigations: locking (one fetcher), request coalescing, or pre-warming before TTL expiry."),
        quiz("cache-5","What is the difference between LRU and LFU eviction?","medium",("caching",),("LRU evicts least recently used; LFU evicts least frequently used","LFU is always better than LRU regardless of the access pattern or workload","LRU tracks access count per key; LFU tracks the timestamp of last access","They are identical algorithms with different names used by different cache vendors"),0,"LRU works well for temporal locality. LFU favors popular items."),
        quiz("cache-6","What is cache warming?","medium",("caching",),("Resetting the cache by clearing all entries and rebuilding indexes from scratch","A type of eviction where entries are removed based on their temperature score","Pre-loading frequently accessed data into cache before traffic arrives","Encrypting cached data at rest using application-managed symmetric keys"),2,"Cache warming prevents cold-start latency spikes after deployments or node replacements."),
        quiz("cache-7","What is the difference between local and distributed cache?","medium",("caching",),("Local caches support all Redis data structures; distributed caches only support strings","Distributed caches are always slower due to network overhead and serialization costs","Local is per-instance in-memory; distributed is shared across instances (Redis, Memcached)","Local caches are more consistent because they avoid network partition issues entirely"),2,"Local caches are fastest but inconsistent across instances. Distributed caches ensure shared state."),
        quiz("cache-8","Why is cache invalidation hard?","hard",("caching",),("Keeping cache in sync with source of truth — hard due to race conditions and timing","Cache invalidation is actually easy; the real challenge is choosing eviction policies","The difficulty is purely in choosing the correct TTL value for each cached entry","Invalidation is hard because most cache systems don't support delete operations natively"),0,"'Two hard things in CS: cache invalidation and naming things.' — Phil Karlton"),
        quiz("cache-9","What is cache penetration?","hard",("caching",),("Cache memory overflow causing entries to spill to disk-based secondary storage","A security attack where malicious input bypasses cache validation and corrupts data","When cache entries are evicted too aggressively, causing unnecessary DB reads on hot data","Requests for non-existent data bypass cache and always hit DB since there's nothing to cache"),3,"Mitigations: cache negative results with short TTL, or use Bloom filter to check existence."),
        quiz("cache-10","What is the 80/20 rule in caching?","easy",("caching",),("Cache should maintain an 80% hit rate to justify its memory cost overhead","You should cache 80% of your total data to guarantee adequate coverage","~80% of requests hit ~20% of data, so caching the hot 20% handles most traffic","After 80 seconds without access, cache entries should be evicted to free memory"),2,"Pareto principle: a small subset of data serves most requests."),
        quiz("cache-11","What is the difference between Memcached and Redis?","medium",("caching",),("They are identical in features; Redis is just the newer version of Memcached","Memcached is newer and supports more data structures than Redis natively","Redis supports data structures, persistence, replication; Memcached is simpler key-value only","Redis cannot form clusters; Memcached has built-in clustering and auto-sharding"),2,"Redis is more feature-rich. Memcached is simpler and can be faster for pure KV workloads."),
        quiz("cache-12","What is a read-through cache?","medium",("caching",),("Same as cache-aside; the application fetches from DB and writes to cache on miss","The cache itself loads data from DB on miss, transparent to the application","A write-only cache that buffers updates and flushes them to the database in batches","A CDN feature that pre-fetches content from the origin based on predicted demand"),1,"Read-through differs from cache-aside: the cache library handles DB fetching, not app code."),
        quiz("cache-13","What is a Bloom filter and how does it help caching?","hard",("caching",),("An eviction policy that removes entries with the lowest access frequency score","A sorting algorithm that orders cache entries by their expiration time for batch eviction","A probabilistic structure that tells if a key definitely doesn't exist or might exist","A hash function that maps cache keys to memory addresses for O(1) direct lookups"),2,"Bloom filters prevent cache penetration: if filter says 'no', the key definitely doesn't exist."),
        quiz("cache-14","When should you NOT use caching?","medium",("caching",),("When using NoSQL databases, since they have built-in caching at the storage layer","When the application uses CDNs, since CDN caching replaces application-level caching","When your application is read-heavy and latency requirements are under 10ms","Data changes very frequently, consistency is critical, or working set is too large for memory"),3,"Caching adds complexity. Skip it for rapidly changing or strongly consistent data."),
        quiz("cache-15","What is cache coherence in multi-level caching?","hard",("caching",),("Different cache levels (L1/L2/CDN/app) may have different versions of the same data","Cache coherence is easy to achieve by setting identical TTL values across all layers","Multi-level caches always maintain consistency through the write-through protocol","Only a CDN issue that doesn't affect application-level or database-level caching"),0,"Multi-level caches need coordinated invalidation or versioned keys for consistency."),
        quiz("cache-16","What is TTL-based invalidation?","medium",("caching",),("Only appropriate for static assets like images that never change after creation","A strategy used exclusively for CDN caching, not for application-level Redis caches","Setting an expiration time on cached entries — simple but data can be stale up to TTL","An approach where data is considered stale only when a newer version is explicitly written"),2,"TTL is simple. Good for config, search results, non-critical data where eventual consistency is OK."),
        quiz("cache-17","What is Redis Cluster and how does it shard?","hard",("caching",),("Redis Cluster uses consistent hashing with virtual nodes on a ring, identical to Cassandra","It doesn't shard; Redis Cluster provides only replication for high availability","Distributes data across nodes using 16384 hash slots mapped to master nodes","Shards data by key prefix convention (e.g., user:* goes to shard 1, order:* to shard 2)"),2,"Redis Cluster assigns each key to one of 16384 hash slots distributed across master nodes."),
        quiz("cache-18","What is the hot key problem in caching?","hard",("caching",),("A security issue where frequently accessed cache keys become targets for timing attacks","Cache keys that have expired but are still being served due to clock synchronization issues","One key receives disproportionate traffic, overwhelming the cache node storing it","Too many keys being created simultaneously, exceeding the cache's key namespace limit"),2,"Solutions: replicate hot keys, use local caches for hot data, or add random suffix to shard the key."),
        quiz("cache-19","What is cache-aside vs refresh-ahead?","hard",("caching",),("They are the same strategy; refresh-ahead is the formal academic name for cache-aside","Refresh-ahead is slower because it blocks reads while refreshing stale cache entries","Cache-aside loads on miss; refresh-ahead proactively refreshes entries before they expire","Cache-aside is proactive and eager; refresh-ahead is lazy and loads data only on demand"),2,"Refresh-ahead reduces cache miss latency by refreshing popular keys before TTL expires."),
        quiz("cache-20","What is the dog-pile effect?","hard",("caching",),("A replication issue where cache followers lag behind the primary by many seconds","A CDN problem where edge nodes repeatedly request the same uncacheable content from origin","An eviction cascade where removing one entry triggers the removal of dependent entries","Multiple processes simultaneously regenerate an expired cache entry, spiking the backend"),3,"Same as cache stampede. Use locking, stale-while-revalidate, or probabilistic early expiration."),
    ))
