"""HLD Core Concepts: Database Indexing, Caching — 20 MCQs each."""
from __future__ import annotations
from .lld_practice import quiz, Lesson

def db_indexing_lesson() -> Lesson:
    return Lesson(id="hld-db-indexing", number=103, title="Database Indexing",
        focus=("B-tree","hash index","composite","covering","LSM tree","bitmap"),
        overview="Indexing is the most impactful DB optimization. Know internals, tradeoffs, and when NOT to index.",
        patterns=(), badge="HLD Core", tasks=(
        quiz("idx-1","What is a B-tree index and why is it the default?","hard",("indexing",),("A binary tree","A balanced tree keeping data sorted for O(log n) lookups, range queries, and ordered scans","A hash function","An in-memory structure"),1,"B-trees are the backbone of relational DB indexes — equality, range, and prefix queries."),
        quiz("idx-2","When would you choose a hash index over a B-tree?","hard",("indexing",),("Always","Only exact-match lookups needed (no range queries), wanting O(1) average performance","When data is sorted","For text search"),1,"Hash indexes are O(1) for point lookups but can't support range, ORDER BY, or prefix matching."),
        quiz("idx-3","What is a composite index?","medium",("indexing",),("Index on all columns","An index on multiple columns, useful when queries filter on combinations","A unique constraint","A foreign key"),1,"Composite indexes follow the leftmost prefix rule: index on (a,b,c) supports (a), (a,b), (a,b,c)."),
        quiz("idx-4","What is a covering index?","hard",("indexing",),("Index covering all tables","An index containing all columns needed for a query, eliminating table lookups","A backup index","A PK index"),1,"Covering indexes avoid table lookups entirely, significantly improving read performance."),
        quiz("idx-5","What is the leftmost prefix rule for composite indexes?","hard",("indexing",),("Use the left columns first in SELECT","An index on (a,b,c) can serve queries on (a), (a,b), (a,b,c) but NOT (b,c) alone","Always start with the leftmost table","Index columns alphabetically"),1,"The index can be used as long as the query filters start from the leftmost column."),
        quiz("idx-6","What is an LSM tree and which databases use it?","hard",("indexing",),("A B-tree variant","A write-optimized structure using memtable+SSTables with compaction — used by Cassandra, RocksDB, LevelDB","A hash table","An in-memory cache"),1,"LSM trees batch writes in memory, flush to sorted files, then compact. Much faster writes than B-trees."),
        quiz("idx-7","What is the difference between a clustered and non-clustered index?","hard",("indexing",),("No difference","Clustered sorts the actual table data (one per table); non-clustered is a separate structure pointing to rows","Non-clustered is faster","Clustered is only for PKs"),1,"A clustered index determines physical row order. A table can have only one clustered index (usually PK)."),
        quiz("idx-8","What is index selectivity and why does it matter?","hard",("indexing",),("How fast the index is","The ratio of distinct values to total rows — higher selectivity means the index is more useful","The number of indexes","How much memory it uses"),1,"An index on a boolean column (selectivity ~50%) is nearly useless. An index on email (high selectivity) is very useful."),
        quiz("idx-9","When should you NOT create an index?","medium",("indexing",),("Never, always index","When the table is small, column has low cardinality, or writes vastly outnumber reads","When using NoSQL","When using views"),1,"Indexes speed reads but slow writes (each INSERT/UPDATE must maintain the index)."),
        quiz("idx-10","What is a partial (filtered) index?","hard",("indexing",),("An incomplete index","An index that only covers rows matching a WHERE condition, saving space and improving performance","A broken index","An index on part of a column"),1,"Example: CREATE INDEX ON orders(status) WHERE status='pending' — only indexes pending orders."),
        quiz("idx-11","What is a bitmap index and when is it useful?","hard",("indexing",),("An image index","Uses bitmaps for each distinct value — efficient for low-cardinality columns in OLAP/analytics","A B-tree variant","A hash index"),1,"Bitmap indexes excel at combining filters (AND/OR) on low-cardinality columns (gender, status, region)."),
        quiz("idx-12","What is EXPLAIN/EXPLAIN ANALYZE used for?","medium",("indexing",),("Creating indexes","Showing the query execution plan — which indexes are used, scan types, estimated costs","Deleting indexes","Optimizing writes"),1,"EXPLAIN reveals if your query uses an index, does a full table scan, or picks the wrong plan."),
        quiz("idx-13","What is a full table scan and when is it acceptable?","medium",("indexing",),("Never acceptable","Reading every row — acceptable for small tables or queries returning a large percentage of rows","The fastest scan","An index scan"),1,"The optimizer may choose a full scan over an index when >20-30% of rows match — the index isn't worth the random I/O."),
        quiz("idx-14","What is an inverted index?","hard",("indexing",),("A reversed B-tree","Maps each unique term to the list of documents containing it — used for full-text search","A hash table","A sorted array"),1,"Elasticsearch and Lucene use inverted indexes: term → [doc1, doc5, doc42] for O(1) term lookups."),
        quiz("idx-15","What is index bloat and how do you fix it?","hard",("indexing",),("Too many indexes","When dead tuples inflate index size due to UPDATE/DELETE without VACUUM — fix with REINDEX or VACUUM","Index is too large","Index corruption"),1,"In PostgreSQL, MVCC creates dead tuples. Without regular VACUUM, indexes grow unnecessarily."),
        quiz("idx-16","What is the write amplification problem with indexes?","hard",("indexing",),("Writes are too small","Each write to the table requires updating every index on that table, multiplying write I/O","Writes are duplicated","A network issue"),1,"A table with 5 indexes means each INSERT does 6 writes (1 table + 5 indexes). More indexes = slower writes."),
        quiz("idx-17","What is a GIN index and when would you use it?","hard",("indexing",),("A B-tree for text","Generalized Inverted Index — for full-text search, JSONB queries, and array containment in PostgreSQL","A hash index","A bitmap index"),1,"GIN indexes handle composite values: full-text search (tsvector), JSONB paths, and array @> operators."),
        quiz("idx-18","What is the difference between a unique index and a unique constraint?","medium",("indexing",),("No difference","Functionally identical in most DBs — unique constraint is declarative, unique index is implementation","Unique index is faster","Constraint doesn't create an index"),1,"In PostgreSQL, a UNIQUE constraint automatically creates a unique index under the hood."),
        quiz("idx-19","How does indexing affect JOIN performance?","hard",("indexing",),("No effect","Indexes on JOIN columns allow index nested loop joins instead of full table scans, dramatically improving performance","JOINs don't use indexes","Only the first table uses indexes"),1,"Index the foreign key columns. Without indexes, JOINs may degrade to O(n×m) nested loop scans."),
        quiz("idx-20","What is an adaptive hash index in InnoDB?","hard",("indexing",),("A manually created hash","An automatic in-memory hash index built by InnoDB for frequently accessed B-tree index pages","A B-tree optimization","A query cache"),1,"InnoDB monitors access patterns and automatically builds hash indexes for hot pages, giving O(1) lookups."),
    ))

def caching_lesson() -> Lesson:
    return Lesson(id="hld-caching", number=104, title="Caching",
        focus=("cache-aside","write-through","eviction","Redis","CDN","invalidation"),
        overview="Caching is the #1 performance optimization. Master strategies, pitfalls, and Redis internals.",
        patterns=(), badge="HLD Core", tasks=(
        quiz("cache-1","What is cache-aside (lazy loading)?","medium",("caching",),("Always read from DB","Check cache → if miss, read from DB → write to cache → return","Write cache first","Read from CDN only"),1,"Cache-aside is the most common pattern. The application manages the cache explicitly."),
        quiz("cache-2","What is write-through caching?","medium",("caching",),("Same as cache-aside","Writes go to cache AND DB simultaneously, keeping cache always up-to-date","Writes skip cache","A read-only strategy"),1,"Write-through ensures cache freshness but adds write latency."),
        quiz("cache-3","What is write-behind (write-back) caching?","hard",("caching",),("Same as write-through","Writes go to cache first, then asynchronously flushed to DB in batches","Writes skip cache","A read-only strategy"),1,"Write-behind improves write performance but risks data loss if cache crashes before flushing."),
        quiz("cache-4","What is cache stampede?","hard",("caching",),("Cache overflow","Many requests simultaneously miss the cache and hit the DB, causing overload","An eviction policy","A CDN failure"),1,"Mitigations: locking (one fetcher), request coalescing, or pre-warming before TTL expiry."),
        quiz("cache-5","What is the difference between LRU and LFU eviction?","medium",("caching",),("Same thing","LRU evicts least recently used; LFU evicts least frequently used","LFU is always better","LRU uses more memory"),1,"LRU works well for temporal locality. LFU favors popular items."),
        quiz("cache-6","What is cache warming?","medium",("caching",),("Resetting the cache","Pre-loading frequently accessed data into cache before traffic arrives","A type of eviction","Encrypting cached data"),1,"Cache warming prevents cold-start latency spikes after deployments or node replacements."),
        quiz("cache-7","What is the difference between local and distributed cache?","medium",("caching",),("Local is always faster","Local is per-instance in-memory; distributed is shared across instances (Redis, Memcached)","Distributed can't use Redis","Local is more consistent"),1,"Local caches are fastest but inconsistent across instances. Distributed caches ensure shared state."),
        quiz("cache-8","Why is cache invalidation hard?","hard",("caching",),("Performance issue","Keeping cache in sync with source of truth — hard due to race conditions, distributed systems, timing","Data encryption","Load balancing"),1,"'Two hard things in CS: cache invalidation and naming things.' — Phil Karlton"),
        quiz("cache-9","What is cache penetration?","hard",("caching",),("Cache overflow","Requests for non-existent data bypass cache and always hit DB","A security attack","Cache eviction"),1,"Mitigations: cache negative results with short TTL, or use Bloom filter to check existence."),
        quiz("cache-10","What is the 80/20 rule in caching?","easy",("caching",),("Cache 80% of data","~80% of requests hit ~20% of data, so caching hot 20% handles most traffic","80% hit rate","Evict after 80s"),1,"Pareto principle: a small subset of data serves most requests."),
        quiz("cache-11","What is the difference between Memcached and Redis?","medium",("caching",),("Identical","Redis supports data structures, persistence, replication; Memcached is simpler KV only","Memcached is newer","Redis can't cluster"),1,"Redis is more feature-rich. Memcached is simpler and can be faster for pure KV workloads."),
        quiz("cache-12","What is a read-through cache?","medium",("caching",),("Same as cache-aside","The cache itself loads data from DB on miss, transparent to the app","A write-only cache","A CDN feature"),1,"Read-through differs from cache-aside: the cache library handles DB fetching, not app code."),
        quiz("cache-13","What is a Bloom filter and how does it help caching?","hard",("caching",),("An eviction policy","A probabilistic structure that tells if a key definitely doesn't exist or might exist, preventing unnecessary DB lookups","A sorting algorithm","A hash function"),1,"Bloom filters prevent cache penetration: if filter says 'no', the key definitely doesn't exist."),
        quiz("cache-14","When should you NOT use caching?","medium",("caching",),("Never, always cache","Data changes very frequently, consistency is critical, or working set is too large for memory","When using NoSQL","When using CDNs"),1,"Caching adds complexity. Skip it for rapidly changing or strongly consistent data."),
        quiz("cache-15","What is cache coherence in multi-level caching?","hard",("caching",),("Cache is too small","Different cache levels (L1/L2/CDN/app) may have different versions of the same data","Cache is too slow","A CDN issue only"),1,"Multi-level caches need coordinated invalidation or versioned keys for consistency."),
        quiz("cache-16","What is TTL-based invalidation?","medium",("caching",),("Never appropriate","Setting an expiration time on cached entries — simple but data can be stale up to TTL duration","Only for images","When data never changes"),1,"TTL is simple. Good for config, search results, non-critical data where eventual consistency is OK."),
        quiz("cache-17","What is Redis Cluster and how does it shard?","hard",("caching",),("It doesn't shard","Distributes data across nodes using 16384 hash slots mapped to master nodes","Uses consistent hashing only","Shards by key prefix"),1,"Redis Cluster assigns each key to one of 16384 hash slots distributed across master nodes."),
        quiz("cache-18","What is the hot key problem in caching?","hard",("caching",),("A security issue","One key receives disproportionate traffic, overwhelming the cache node storing it","Too many keys","Key expiration"),1,"Solutions: replicate hot keys, use local caches for hot data, or add a random suffix to shard the key."),
        quiz("cache-19","What is cache-aside vs refresh-ahead?","hard",("caching",),("Same thing","Cache-aside loads on miss; refresh-ahead proactively refreshes entries before they expire","Refresh-ahead is slower","Cache-aside is proactive"),1,"Refresh-ahead reduces cache miss latency by refreshing popular keys before TTL expires."),
        quiz("cache-20","What is the dog-pile effect?","hard",("caching",),("A replication issue","Multiple processes simultaneously regenerate an expired cache entry, causing a spike on the backend","A CDN problem","An eviction issue"),1,"Same as cache stampede. Use locking, stale-while-revalidate, or probabilistic early expiration."),
    ))
