"""HLD MCQs — System Design Patterns and Key Technologies."""
from __future__ import annotations
from .lld_practice import quiz, Lesson


def patterns_lesson() -> Lesson:
    return Lesson(
        id="hld-patterns", number=106, title="System Design Patterns",
        focus=("real-time", "contention", "scaling", "sagas", "CQRS", "event sourcing"),
        overview="These patterns appear in almost every system design interview. Know when and why to apply each.",
        patterns=(), badge="HLD",
        tasks=(
            quiz("pat-1", "What is CQRS and when would you use it?",
                 "hard", ("patterns", "cqrs"),
                 ("A caching strategy", "Command Query Responsibility Segregation — separate read and write models when they have very different requirements", "A database type", "A load balancing technique"), 1,
                 "CQRS lets you optimize reads and writes independently. Common in event-sourced systems and high-read:write ratio apps."),
            quiz("pat-2", "What is event sourcing?",
                 "hard", ("patterns", "event-sourcing"),
                 ("Logging errors", "Storing all state changes as an immutable sequence of events instead of just the current state", "A message queue pattern", "Database sharding"), 1,
                 "Event sourcing gives you complete audit trails, time travel, and the ability to rebuild state from events."),
            quiz("pat-3", "What is the Saga pattern for distributed transactions?",
                 "hard", ("patterns", "saga"),
                 ("A long database transaction", "A sequence of local transactions where each step has a compensating action for rollback", "A type of 2PC", "A caching pattern"), 1,
                 "Sagas handle distributed transactions without 2PC. Choreography (events) or Orchestration (coordinator) are the two approaches."),
            quiz("pat-4", "What is the difference between choreography and orchestration sagas?",
                 "hard", ("patterns", "saga"),
                 ("No difference", "Choreography: services react to events. Orchestration: a central coordinator directs the steps", "Orchestration is decentralized", "Choreography uses a coordinator"), 1,
                 "Choreography is more decoupled but harder to debug. Orchestration is centralized and easier to reason about."),
            quiz("pat-5", "What is the fan-out/fan-in pattern?",
                 "medium", ("patterns",),
                 ("A caching strategy", "Distribute work to many workers (fan-out), collect and aggregate results (fan-in)", "A database pattern", "A load balancing technique"), 1,
                 "Fan-out/fan-in is used for parallel processing: send work to N workers, aggregate N results. Common in news feeds and search."),
            quiz("pat-6", "What is the difference between push and pull models for news feeds?",
                 "hard", ("patterns", "feed"),
                 ("They are the same", "Push (fan-out on write): precompute feeds on post. Pull (fan-out on read): compute feed at read time", "Push is always better", "Pull doesn't use caching"), 1,
                 "Push is good for users with few followers. Pull is better for celebrities (millions of followers would make push too expensive)."),
            quiz("pat-7", "What is the outbox pattern?",
                 "hard", ("patterns",),
                 ("A logging technique", "Write events to an outbox table in the same DB transaction, then a separate process publishes them to the message broker", "An email pattern", "A caching strategy"), 1,
                 "The outbox pattern ensures atomicity between DB writes and event publishing, avoiding dual-write problems."),
            quiz("pat-8", "What is back-pressure and how is it implemented?",
                 "hard", ("patterns", "resilience"),
                 ("A compression technique", "When a consumer signals it's overwhelmed, upstream producers slow down — via queue limits, flow control, or rate limiting", "A caching strategy", "A load balancer feature"), 1,
                 "Without back-pressure, fast producers overwhelm slow consumers. Kafka consumer groups and reactive streams handle this."),
            quiz("pat-9", "What is the bulkhead pattern?",
                 "hard", ("patterns", "resilience"),
                 ("A storage pattern", "Isolating components so a failure in one doesn't cascade to others, like watertight compartments in a ship", "A caching strategy", "A sharding technique"), 1,
                 "Bulkheads isolate failure domains: separate thread pools, connection pools, or even services for different features."),
            quiz("pat-10", "What is event-driven architecture?",
                 "medium", ("patterns",),
                 ("A synchronous request/response model", "Components communicate by producing and consuming events asynchronously via a message broker", "A database architecture", "A caching pattern"), 1,
                 "Event-driven architecture decouples producers from consumers, enabling scalability and loose coupling."),
            quiz("pat-11", "When would you use a message queue vs. direct API calls?",
                 "medium", ("patterns",),
                 ("Always use queues", "Queues for async, fire-and-forget, decoupling, and load leveling; API calls for sync, immediate responses", "Always use API calls", "Queues are slower"), 1,
                 "Queues absorb traffic spikes, decouple services, and enable retry/dead-letter handling."),
            quiz("pat-12", "What is the strangler fig pattern?",
                 "hard", ("patterns",),
                 ("A database migration", "Gradually replacing a legacy system by routing traffic to a new system piece by piece", "A caching strategy", "A load balancing technique"), 1,
                 "The strangler fig pattern allows incremental migration without big-bang rewrites. Route by feature/endpoint."),
            quiz("pat-13", "What is a dead letter queue?",
                 "medium", ("patterns",),
                 ("A deleted queue", "A queue where messages that fail processing after max retries are sent for later investigation", "A logging mechanism", "A backup queue"), 1,
                 "DLQs prevent poison messages from blocking a queue. Failed messages are parked for debugging/reprocessing."),
            quiz("pat-14", "What is the sidecar pattern?",
                 "hard", ("patterns", "microservices"),
                 ("A secondary database", "A helper process deployed alongside a service to handle cross-cutting concerns like logging, monitoring, or networking", "A load balancer", "A caching layer"), 1,
                 "Sidecars (like Envoy in a service mesh) add capabilities without modifying the main service code."),
            quiz("pat-15", "What is leader election in distributed systems?",
                 "hard", ("patterns", "distributed"),
                 ("Choosing a database", "A process where nodes agree on one node to act as coordinator for critical tasks", "A load balancing algorithm", "A replication strategy"), 1,
                 "Leader election (via Raft, Paxos, or ZooKeeper) ensures only one node performs a critical operation at a time."),
            quiz("pat-16", "What is the competing consumers pattern?",
                 "medium", ("patterns",),
                 ("Multiple caches", "Multiple consumers read from the same queue, each processing different messages for parallel throughput", "A database pattern", "A conflict resolution strategy"), 1,
                 "Competing consumers scale processing by adding more workers. Each message is processed by exactly one consumer."),
            quiz("pat-17", "What is two-phase commit (2PC) and why is it problematic?",
                 "hard", ("patterns", "distributed"),
                 ("A caching technique", "A protocol for atomic distributed transactions: prepare phase → commit phase. Problematic due to blocking and coordinator SPOF", "A load balancing algorithm", "A database index"), 1,
                 "2PC guarantees atomicity but blocks all participants if the coordinator fails. Sagas are preferred in microservices."),
            quiz("pat-18", "What is the write-ahead log (WAL) pattern in distributed systems?",
                 "hard", ("patterns",),
                 ("A caching technique", "Write changes to an append-only log before applying them, ensuring durability and enabling replication", "A load balancing technique", "An API design pattern"), 1,
                 "WAL is the backbone of database durability, Kafka (commit log), and distributed consensus (Raft log)."),
            quiz("pat-19", "What is change data capture (CDC)?",
                 "hard", ("patterns",),
                 ("Backing up data", "Tracking and streaming database changes as events, enabling downstream systems to react to data changes", "A caching strategy", "A migration tool"), 1,
                 "CDC (via Debezium, DynamoDB Streams) turns DB changes into event streams for search indexing, caching, or analytics."),
            quiz("pat-20", "What is the ambassador pattern?",
                 "hard", ("patterns", "microservices"),
                 ("A security pattern", "A proxy that sits between a service and external systems, handling retries, circuit breaking, and monitoring", "A database pattern", "A message queue"), 1,
                 "Ambassador offloads networking concerns from the service. It's related to the sidecar pattern."),
            quiz("pat-21", "What is token bucket rate limiting?",
                 "hard", ("patterns", "rate-limiting"),
                 ("A caching technique", "Tokens are added to a bucket at a fixed rate; each request consumes a token; requests are rejected when the bucket is empty", "A database index", "A load balancing algorithm"), 1,
                 "Token bucket allows bursts (up to bucket capacity) while enforcing average rate. Used by most API rate limiters."),
            quiz("pat-22", "What is sliding window rate limiting?",
                 "hard", ("patterns", "rate-limiting"),
                 ("Same as fixed window", "Tracks requests in a continuously moving time window, providing smoother rate enforcement than fixed windows", "A caching strategy", "A database technique"), 1,
                 "Sliding window avoids the burst-at-boundary problem of fixed windows. Implementations: sliding window log or counter."),
            quiz("pat-23", "What is the difference between at-least-once and exactly-once delivery?",
                 "hard", ("patterns", "messaging"),
                 ("They are the same", "At-least-once may deliver duplicates; exactly-once guarantees no duplicates (hard to achieve, often needs idempotency)", "At-least-once is more reliable", "Exactly-once is simpler"), 1,
                 "True exactly-once is nearly impossible. In practice: at-least-once delivery + idempotent consumers = effectively-once."),
            quiz("pat-24", "What is the CRDT approach to handling conflicts?",
                 "hard", ("patterns", "distributed"),
                 ("A consensus protocol", "Conflict-free Replicated Data Types that can be merged automatically without coordination", "A caching strategy", "A sharding technique"), 1,
                 "CRDTs (counters, sets, maps) allow concurrent writes without conflicts — used in collaborative editing and AP systems."),
            quiz("pat-25", "What is the materialized view pattern?",
                 "medium", ("patterns",),
                 ("A database index", "Pre-computing and storing query results to serve reads faster, updated asynchronously or on write", "A caching layer", "A message queue"), 1,
                 "Materialized views denormalize data for read performance. Common in CQRS where the read model is a projection of events."),
        ),
    )


def technologies_lesson() -> Lesson:
    return Lesson(
        id="hld-technologies", number=107, title="Key Technologies Deep Dive",
        focus=("Redis", "Kafka", "Elasticsearch", "Cassandra", "DynamoDB", "PostgreSQL", "ZooKeeper"),
        overview="Know the internals, tradeoffs, and sweet spots of the technologies interviewers expect you to use.",
        patterns=(), badge="HLD",
        tasks=(
            quiz("tech-1", "What makes Kafka different from a traditional message queue?",
                 "hard", ("kafka",),
                 ("Kafka is faster", "Kafka is a distributed commit log that retains messages, allowing replay and multiple consumer groups", "Kafka is simpler", "Kafka doesn't guarantee ordering"), 1,
                 "Unlike RabbitMQ, Kafka retains messages after consumption. Consumers track their offset. Messages can be replayed."),
            quiz("tech-2", "What is a Kafka partition and why does it matter?",
                 "hard", ("kafka",),
                 ("A database shard", "The unit of parallelism — messages are ordered within a partition, and partitions are distributed across brokers", "A topic", "A consumer group"), 1,
                 "Partitions enable horizontal scaling. Ordering is only guaranteed within a partition, not across partitions."),
            quiz("tech-3", "What is a Kafka consumer group?",
                 "medium", ("kafka",),
                 ("A group of topics", "A set of consumers that share partition ownership — each partition is consumed by exactly one consumer in the group", "A broker cluster", "A replication mechanism"), 1,
                 "Consumer groups enable parallel processing. If you have 10 partitions, you can have up to 10 consumers in a group."),
            quiz("tech-4", "What happens when a Kafka consumer falls behind?",
                 "hard", ("kafka",),
                 ("Messages are deleted", "The consumer's offset lags — it can catch up by reading from disk (Kafka stores messages for a configurable retention period)", "Kafka stops producers", "The topic is paused"), 1,
                 "Kafka's retention (time or size based) allows slow consumers to catch up. Consumer lag is a key metric to monitor."),
            quiz("tech-5", "What is Elasticsearch optimized for?",
                 "medium", ("elasticsearch",),
                 ("ACID transactions", "Full-text search, analytics, and log aggregation using inverted indexes", "Graph traversal", "Time-series storage only"), 1,
                 "ES uses inverted indexes for fast text search. It's also great for log analytics (ELK stack) and fuzzy matching."),
            quiz("tech-6", "What is an inverted index in Elasticsearch?",
                 "hard", ("elasticsearch",),
                 ("A B-tree index", "A data structure mapping each unique term to the list of documents containing it", "A hash table", "A sorted array"), 1,
                 "Inverted index: term → [doc1, doc5, doc42]. This enables O(1) lookup of which documents contain a search term."),
            quiz("tech-7", "What is the difference between Cassandra and DynamoDB?",
                 "hard", ("cassandra", "dynamodb"),
                 ("They are the same", "Both are wide-column/KV stores. Cassandra is self-hosted with tunable consistency; DynamoDB is managed AWS with provisioned/on-demand capacity", "DynamoDB is open source", "Cassandra is managed only"), 1,
                 "Cassandra: open-source, tunable consistency, requires ops. DynamoDB: fully managed, pay-per-use, AWS-only."),
            quiz("tech-8", "What is Cassandra's data model based on?",
                 "hard", ("cassandra",),
                 ("Relational tables", "Partition key + clustering columns — queries must include the partition key", "JSON documents", "Graph nodes"), 1,
                 "Cassandra designs around query patterns. The partition key determines data placement; clustering columns sort within partitions."),
            quiz("tech-9", "What is ZooKeeper used for in distributed systems?",
                 "hard", ("zookeeper",),
                 ("Message queuing", "Distributed coordination: leader election, configuration management, service discovery, and distributed locking", "File storage", "Search indexing"), 1,
                 "ZooKeeper provides primitives for coordination. Used by Kafka, HBase, and Hadoop for leader election and config."),
            quiz("tech-10", "What is Redis Sorted Set and when would you use it?",
                 "hard", ("redis",),
                 ("A hash table", "A set where each member has a score, supporting O(log n) ranked queries — ideal for leaderboards", "A linked list", "A queue"), 1,
                 "ZADD/ZRANGE/ZRANK: perfect for leaderboards, priority queues, and time-windowed aggregations."),
            quiz("tech-11", "What is PostgreSQL's MVCC?",
                 "hard", ("postgresql",),
                 ("A caching mechanism", "Multi-Version Concurrency Control — each transaction sees a snapshot, allowing concurrent reads/writes without blocking", "A replication protocol", "An index type"), 1,
                 "MVCC: readers don't block writers, writers don't block readers. Each row version has a transaction visibility range."),
            quiz("tech-12", "What is Apache Flink used for?",
                 "hard", ("flink",),
                 ("Batch processing only", "Real-time stream processing with exactly-once semantics and stateful computations", "File storage", "Database management"), 1,
                 "Flink processes unbounded streams with event-time semantics, windowing, and checkpointing for fault tolerance."),
            quiz("tech-13", "What is the difference between Kafka and RabbitMQ?",
                 "hard", ("kafka",),
                 ("No difference", "Kafka retains messages (log-based, replay); RabbitMQ deletes after ack (queue-based, push model)", "RabbitMQ is faster", "Kafka doesn't support ordering"), 1,
                 "Kafka: high throughput, replay, ordering within partitions. RabbitMQ: flexible routing, low latency, traditional queue semantics."),
            quiz("tech-14", "What is DynamoDB's partition key and sort key?",
                 "hard", ("dynamodb",),
                 ("Same as SQL primary key", "Partition key determines data placement; sort key enables range queries within a partition", "They are optional", "Sort key is for sorting results only"), 1,
                 "DynamoDB's composite key (PK + SK) is the foundation of its data model and query capabilities."),
            quiz("tech-15", "What is the ELK stack?",
                 "medium", ("elasticsearch",),
                 ("A database cluster", "Elasticsearch (search/analytics) + Logstash (ingestion/transformation) + Kibana (visualization)", "A caching layer", "A CDN"), 1,
                 "ELK is the go-to for log aggregation, monitoring, and observability in distributed systems."),
            quiz("tech-16", "What is Redis Streams and how does it differ from pub/sub?",
                 "hard", ("redis",),
                 ("They are the same", "Streams persist messages with consumer groups and acknowledgments; pub/sub is fire-and-forget", "Pub/sub is persistent", "Streams are slower"), 1,
                 "Redis Streams (XADD/XREAD/XACK) provide Kafka-like semantics: persistent, consumer groups, message acknowledgment."),
            quiz("tech-17", "What is Cassandra's gossip protocol?",
                 "hard", ("cassandra",),
                 ("A consensus algorithm", "A peer-to-peer protocol where nodes periodically exchange state information to maintain cluster membership", "A query protocol", "A replication mechanism"), 1,
                 "Gossip propagates cluster state (which nodes are alive/dead) without a central coordinator. Eventually consistent."),
            quiz("tech-18", "What is PostgreSQL's WAL and why does it matter?",
                 "hard", ("postgresql",),
                 ("A caching mechanism", "Write-Ahead Log records changes before they're applied, ensuring crash recovery and enabling replication", "An index type", "A query optimizer"), 1,
                 "WAL is how PostgreSQL provides durability (D in ACID) and enables streaming replication to followers."),
            quiz("tech-19", "What is the difference between Elasticsearch and Solr?",
                 "medium", ("elasticsearch",),
                 ("They are completely different", "Both are Lucene-based search engines. ES has better distributed/scaling model and REST API; Solr is more mature for traditional search", "Solr is newer", "ES doesn't support full-text search"), 1,
                 "Both use Apache Lucene. ES dominates for analytics/observability; Solr is strong for classic enterprise search."),
            quiz("tech-20", "When would you use an API Gateway like Kong or AWS API Gateway?",
                 "medium", ("api-gateway",),
                 ("For database queries", "To centralize auth, rate limiting, routing, protocol translation, and monitoring for microservices", "For file storage", "For message queuing"), 1,
                 "API Gateways simplify client-to-microservice communication by handling cross-cutting concerns in one place."),
            quiz("tech-21", "What is Redis' single-threaded model and why does it still perform well?",
                 "hard", ("redis",),
                 ("It uses multi-threading", "Single-threaded event loop avoids locking overhead; all operations are in-memory and O(1)/O(log n)", "It doesn't perform well", "It uses processes instead"), 1,
                 "Redis is CPU-bound rarely. In-memory ops are so fast that one thread saturates network bandwidth before CPU."),
            quiz("tech-22", "What is Kafka Connect?",
                 "medium", ("kafka",),
                 ("A client library", "A framework for streaming data between Kafka and external systems (databases, ES, S3) via source/sink connectors", "A monitoring tool", "A security module"), 1,
                 "Kafka Connect eliminates custom integration code. Source connectors ingest data; sink connectors export data."),
            quiz("tech-23", "What is DynamoDB's on-demand vs. provisioned capacity?",
                 "medium", ("dynamodb",),
                 ("No difference", "On-demand auto-scales and charges per request; provisioned requires pre-set RCU/WCU and is cheaper for predictable workloads", "On-demand is always cheaper", "Provisioned is deprecated"), 1,
                 "On-demand is simpler but 6-7x more expensive per request. Provisioned with auto-scaling is the common production choice."),
            quiz("tech-24", "What is ZooKeeper's ZAB protocol?",
                 "hard", ("zookeeper",),
                 ("A caching protocol", "ZooKeeper Atomic Broadcast — a consensus protocol that ensures all nodes agree on the order of state changes", "A gossip protocol", "A load balancing algorithm"), 1,
                 "ZAB is similar to Raft/Paxos. The leader broadcasts proposals; followers acknowledge. Quorum required for commit."),
            quiz("tech-25", "What problem does a service mesh (Istio/Linkerd) solve?",
                 "hard", ("service-mesh",),
                 ("Database scaling", "Manages service-to-service communication: mTLS, load balancing, retries, observability — without changing application code", "Message queuing", "Search indexing"), 1,
                 "A service mesh uses sidecar proxies to handle networking concerns, making microservice communication reliable and observable."),
        ),
    )
