"""HLD MCQs — System Design Question Breakdowns: actual interview design decisions."""
from __future__ import annotations
from .lld_practice import quiz, Lesson


def design_questions_lesson() -> Lesson:
    return Lesson(
        id="hld-design-questions", number=108, title="System Design Question Breakdowns",
        focus=("URL shortener", "chat", "feed", "storage", "ride sharing", "video", "payments"),
        overview="These are the actual design questions asked in FAANG interviews. Know the key decisions for each.",
        patterns=(), badge="HLD",
        tasks=(
            quiz("dq-1", "For designing a URL shortener (Bitly), what is the best approach for generating short URLs?",
                 "hard", ("url-shortener",),
                 ("Auto-increment IDs", "Base62 encoding of a counter or hash, with collision checking", "Random strings with no uniqueness check", "Hashing the full URL with MD5"), 1,
                 "Base62 encoding of a counter/ID gives short, unique URLs. Hash-based approaches need collision detection."),
            quiz("dq-2", "For a URL shortener, why would you use a distributed ID generator instead of a single counter?",
                 "hard", ("url-shortener",),
                 ("Counters are too slow", "A single counter is a SPOF and bottleneck; distributed generators (Snowflake-like) enable horizontal scaling", "Distributed IDs are shorter", "Counters create sequential URLs"), 1,
                 "Range-based partitioning of the ID space or Snowflake IDs avoid the single-counter bottleneck."),
            quiz("dq-3", "For designing WhatsApp, what protocol is best for real-time message delivery?",
                 "hard", ("chat",),
                 ("HTTP polling", "WebSockets for persistent bidirectional connections with MQTT or custom protocol", "SMTP", "FTP"), 1,
                 "WebSockets maintain an open connection. MQTT is lightweight for mobile. HTTP polling wastes bandwidth and adds latency."),
            quiz("dq-4", "For WhatsApp, how do you handle message delivery to offline users?",
                 "hard", ("chat",),
                 ("Discard the message", "Store messages in a queue/DB; deliver when the user reconnects and sends a delivery receipt", "Send via email instead", "Retry indefinitely"), 1,
                 "Store-and-forward: persist undelivered messages, deliver on reconnect, mark as delivered/read with receipts."),
            quiz("dq-5", "For designing Instagram/Facebook News Feed, which is better: push or pull model?",
                 "hard", ("feed",),
                 ("Always push", "Hybrid: push for regular users, pull for celebrity accounts with millions of followers", "Always pull", "Neither, use polling"), 1,
                 "Push (fan-out on write) is O(followers) per post. For celebrities, that's millions of writes. Hybrid avoids this."),
            quiz("dq-6", "For designing Dropbox, how should you handle large file uploads?",
                 "hard", ("storage",),
                 ("Upload entire file in one request", "Split into chunks, upload each with checksum, resume on failure, deduplicate", "Use FTP", "Compress and upload"), 1,
                 "Chunked upload with checksums enables resumability, deduplication, and efficient bandwidth usage."),
            quiz("dq-7", "For Dropbox, what is content-addressable storage?",
                 "hard", ("storage",),
                 ("Storing by filename", "Addressing blocks by their content hash (SHA-256), enabling deduplication across all users", "A type of CDN", "A database index"), 1,
                 "If two users upload the same file, the blocks hash to the same address — store once, reference many times."),
            quiz("dq-8", "For designing Uber, how do you efficiently find nearby drivers?",
                 "hard", ("ride-sharing",),
                 ("Scan all drivers", "Use geospatial indexing (geohash, quadtree, or R-tree) to find drivers within a radius", "Sort by distance", "Use a load balancer"), 1,
                 "Geohash converts 2D coordinates to 1D strings for efficient range queries. S2 cells (Google) or H3 (Uber) are alternatives."),
            quiz("dq-9", "For Uber, how do you handle the matching of riders to drivers?",
                 "hard", ("ride-sharing",),
                 ("First-come-first-serve", "Find nearby available drivers, rank by distance/ETA, send request with timeout, cascade to next if declined", "Random assignment", "Assign the cheapest driver"), 1,
                 "The dispatch service queries nearby drivers, scores them (distance, rating, acceptance rate), and offers sequentially."),
            quiz("dq-10", "For designing YouTube, how do you handle video transcoding?",
                 "hard", ("video",),
                 ("Transcode on the fly", "Use a job queue to asynchronously transcode uploaded videos into multiple resolutions/formats", "Store only one format", "Let the client transcode"), 1,
                 "Videos are transcoded into multiple formats (480p/720p/1080p/4K) and adaptive bitrate (HLS/DASH) for different devices/networks."),
            quiz("dq-11", "For YouTube, how is adaptive bitrate streaming implemented?",
                 "hard", ("video",),
                 ("One quality for all", "Videos are split into small chunks at multiple qualities; the player switches quality based on bandwidth", "CDN handles quality", "The server adjusts quality"), 1,
                 "HLS/DASH protocols: manifest file lists chunk URLs at each quality. The player monitors bandwidth and switches dynamically."),
            quiz("dq-12", "For designing a payment system (like Stripe), what is the most critical requirement?",
                 "hard", ("payments",),
                 ("Low latency", "Exactly-once processing via idempotency keys to prevent duplicate charges", "High throughput", "Beautiful UI"), 1,
                 "A duplicate charge loses customer trust. Idempotency keys + event sourcing + reconciliation are essential."),
            quiz("dq-13", "For a payment system, why is the ledger pattern important?",
                 "hard", ("payments",),
                 ("For tax reporting only", "Double-entry bookkeeping ensures every debit has a matching credit, making the system auditable and self-balancing", "For performance", "For caching"), 1,
                 "Ledger: every transaction creates debit + credit entries. Sum of all entries = 0. This is how real financial systems work."),
            quiz("dq-14", "For designing Ticketmaster, how do you prevent overselling?",
                 "hard", ("ticketmaster",),
                 ("First-come-first-serve with no locking", "Temporary seat reservations with TTL, atomic inventory decrement, and distributed locking", "Let users fight for seats", "Oversell and apologize"), 1,
                 "Reserve seat with TTL (e.g., 10 min), decrement inventory atomically (Redis DECR or DB row lock), release on timeout."),
            quiz("dq-15", "For designing a rate limiter, which algorithm handles burst traffic best?",
                 "hard", ("rate-limiter",),
                 ("Fixed window counter", "Token bucket — allows bursts up to bucket capacity while maintaining average rate", "Leaky bucket", "No rate limiting"), 1,
                 "Token bucket allows controlled bursts. Leaky bucket enforces strict constant rate. Fixed window has boundary burst issues."),
            quiz("dq-16", "For designing Google Docs, how do you handle simultaneous editing?",
                 "hard", ("collaboration",),
                 ("Lock the document", "Operational Transformation (OT) or CRDTs to merge concurrent edits in real-time", "Last write wins", "Queue edits sequentially"), 1,
                 "OT transforms concurrent operations to preserve intent. CRDTs merge without coordination. Google Docs uses OT."),
            quiz("dq-17", "For designing a web crawler, how do you handle politeness?",
                 "hard", ("crawler",),
                 ("Crawl as fast as possible", "Respect robots.txt, limit requests per domain per second, use exponential backoff on errors", "Only crawl once", "Use a CDN"), 1,
                 "Politeness prevents overwhelming target servers. Respect robots.txt, rate limit per domain, and handle 429s gracefully."),
            quiz("dq-18", "For designing Yelp/nearby search, what data structure enables geospatial queries?",
                 "hard", ("geospatial",),
                 ("B-tree", "Quadtree or geohash index for partitioning 2D space into searchable regions", "Hash table", "Linked list"), 1,
                 "Quadtrees recursively divide 2D space into quadrants. Geohash converts lat/lng to a sortable string for range queries."),
            quiz("dq-19", "For designing a distributed cache, what happens during a node failure?",
                 "hard", ("distributed-cache",),
                 ("All data is lost", "With consistent hashing, only keys on the failed node are redistributed to the next node on the ring", "Nothing happens", "The cache restarts"), 1,
                 "Consistent hashing minimizes redistribution. Replicas on adjacent nodes can serve requests immediately."),
            quiz("dq-20", "For designing a notification system, how do you handle millions of push notifications?",
                 "hard", ("notifications",),
                 ("Send sequentially", "Use a message queue to fan out to workers, each batch-sending via APNS/FCM with rate limiting and retry", "Use email instead", "Let the client poll"), 1,
                 "Message queue → workers → APNS/FCM. Handle failures with retries, DLQ, and device token invalidation."),
            quiz("dq-21", "For designing a job scheduler, what is the key challenge?",
                 "hard", ("scheduler",),
                 ("Choosing a language", "Ensuring exactly-once execution, handling failures/retries, and distributing jobs across workers without duplication", "Making it fast", "Adding a UI"), 1,
                 "Use distributed locking or leader election + idempotent jobs. Track state in DB. Handle timeouts and retries."),
            quiz("dq-22", "For designing an ad click aggregator, why is real-time aggregation hard?",
                 "hard", ("aggregation",),
                 ("Ads are complex", "High volume (millions/sec), need for deduplication, late-arriving events, and exactly-once counting", "It's not hard", "Ads are small"), 1,
                 "Stream processing (Flink/Spark) with watermarks for late events, idempotent writes, and pre-aggregation windows."),
            quiz("dq-23", "For designing Tinder, how do you implement the matching algorithm efficiently?",
                 "hard", ("matching",),
                 ("Compare all users", "Use geospatial index for nearby users, filter by preferences, pre-compute match pools, serve from cache", "Random matching", "Sequential scanning"), 1,
                 "Geohash for location filtering, preference-based filtering, pre-computed pools refreshed periodically, Redis for fast serving."),
            quiz("dq-24", "For designing a metrics monitoring system (Datadog), what storage is ideal?",
                 "hard", ("monitoring",),
                 ("PostgreSQL", "Time-series database (InfluxDB, TimescaleDB) optimized for append-heavy, timestamp-ordered data with automatic downsampling", "MongoDB", "Redis"), 1,
                 "Time-series DBs handle high write throughput, time-range queries, retention policies, and automatic rollups efficiently."),
            quiz("dq-25", "For designing ChatGPT's backend, what is the key challenge with LLM serving?",
                 "hard", ("llm",),
                 ("Storing prompts", "High GPU memory usage, long inference latency, streaming token-by-token responses, and scaling GPU clusters", "Database design", "API versioning"), 1,
                 "LLM serving: GPU memory management (KV cache), batching requests, streaming via SSE, and load balancing across GPU nodes."),
            quiz("dq-26", "For a social network, what is the fan-out problem and how does it affect feed design?",
                 "hard", ("feed",),
                 ("Too many fans", "When a user with N followers posts, N feed entries must be created — push model becomes expensive for popular users", "A caching issue", "A database problem"), 1,
                 "Fan-out factor = followers × post rate. Solution: push for normal users, pull for high-follower users."),
            quiz("dq-27", "For designing a price tracking service, how do you detect price changes efficiently?",
                 "hard", ("tracking",),
                 ("Check every second", "Crawl product pages periodically, compare with stored prices, notify users on changes via event-driven pipeline", "Manual checking", "Use a CDN"), 1,
                 "Scheduler → crawler → compare with DB → publish change event → notification service. Prioritize popular/volatile products."),
            quiz("dq-28", "For an online auction system, how do you handle bid contention?",
                 "hard", ("auction",),
                 ("No locking needed", "Use optimistic locking or atomic compare-and-swap to ensure only the highest valid bid wins without race conditions", "Queue all bids sequentially", "Lock the entire database"), 1,
                 "Atomic operations: read current highest → compare → update if higher. Redis WATCH/MULTI or DB row-level locks."),
            quiz("dq-29", "For designing Strava/fitness tracking, how do you store and query GPS trace data?",
                 "hard", ("geospatial",),
                 ("As text strings", "As polyline-encoded sequences stored in a time-series or geospatial database, indexed by user and time range", "As images", "As CSV files"), 1,
                 "Store GPS points as time-series data. Use polyline encoding for compact storage. Geospatial index for route-based queries."),
            quiz("dq-30", "For designing LeetCode's online judge, how do you safely execute user-submitted code?",
                 "hard", ("code-execution",),
                 ("Run directly on the server", "Use sandboxed containers (Docker) with resource limits (CPU, memory, time), network isolation, and read-only filesystem", "Use eval()", "Run in the browser"), 1,
                 "Sandboxing prevents malicious code. Containers provide isolation. cgroups enforce resource limits. seccomp restricts syscalls."),
        ),
    )
