"""HLD System Design MCQs — Core Concepts: Networking, API Design, Data Modeling, Indexing."""
from __future__ import annotations
from .lld_practice import quiz, Lesson, Task


def networking_lesson() -> Lesson:
    return Lesson(
        id="hld-networking", number=100, title="Networking Essentials",
        focus=("TCP/UDP", "HTTP", "DNS", "WebSockets", "load balancing"),
        overview="Understand the networking building blocks that appear in every system design interview.",
        patterns=(), badge="HLD",
        tasks=(
            quiz("net-1", "What is the key difference between TCP and UDP?",
                 "medium", ("networking",),
                 ("TCP is faster, UDP is slower", "TCP guarantees delivery and ordering; UDP does not", "UDP is encrypted, TCP is not", "TCP is connectionless, UDP is connection-oriented"), 1,
                 "TCP provides reliable, ordered delivery via handshakes and acknowledgments. UDP sacrifices that for lower latency."),
            quiz("net-2", "Why would you choose UDP over TCP for a live video streaming service?",
                 "medium", ("networking", "tradeoffs"),
                 ("UDP is more secure", "Lower latency — a few dropped frames are acceptable vs. head-of-line blocking", "UDP handles larger payloads", "UDP has built-in encryption"), 1,
                 "For real-time media, occasional packet loss is preferable to TCP's retransmission delays."),
            quiz("net-3", "What does DNS resolve?",
                 "easy", ("networking", "dns"),
                 ("IP addresses to MAC addresses", "Domain names to IP addresses", "Ports to services", "URLs to file paths"), 1,
                 "DNS maps human-readable domain names to IP addresses."),
            quiz("net-4", "In a system design, what is the primary role of a load balancer?",
                 "easy", ("networking", "load-balancing"),
                 ("Encrypt traffic", "Distribute incoming traffic across multiple servers", "Cache responses", "Manage DNS records"), 1,
                 "Load balancers distribute requests to prevent any single server from being overwhelmed."),
            quiz("net-5", "What is the difference between L4 and L7 load balancing?",
                 "hard", ("networking", "load-balancing"),
                 ("L4 works at the transport layer (TCP/UDP); L7 works at the application layer (HTTP)", "L4 is slower than L7", "L7 cannot handle HTTPS", "L4 inspects request body, L7 does not"), 0,
                 "L4 routes based on IP/port; L7 can make decisions based on HTTP headers, paths, cookies, etc."),
            quiz("net-6", "When would you use WebSockets instead of HTTP polling?",
                 "medium", ("networking", "real-time"),
                 ("When you need file uploads", "When the server needs to push data to clients in real-time with low latency", "When you need caching", "When requests are infrequent"), 1,
                 "WebSockets maintain a persistent bidirectional connection, ideal for chat, live feeds, and gaming."),
            quiz("net-7", "What is Server-Sent Events (SSE) best suited for?",
                 "medium", ("networking", "real-time"),
                 ("Bidirectional communication", "Unidirectional server-to-client streaming over HTTP", "File downloads", "Database replication"), 1,
                 "SSE is simpler than WebSockets for one-way server push (e.g., live scores, notifications)."),
            quiz("net-8", "What is the purpose of a CDN in system design?",
                 "easy", ("networking", "cdn"),
                 ("Database replication", "Serve static content from edge servers geographically closer to users", "Load balance API requests", "Encrypt all traffic"), 1,
                 "CDNs cache and serve static assets from edge locations, reducing latency and origin load."),
            quiz("net-9", "What does a reverse proxy do?",
                 "medium", ("networking",),
                 ("Hides the client's identity from the server", "Sits in front of servers and forwards client requests to backend servers", "Replaces DNS", "Encrypts database connections"), 1,
                 "A reverse proxy accepts client requests and routes them to appropriate backend servers, providing load balancing, SSL termination, and caching."),
            quiz("net-10", "What is the 'thundering herd' problem?",
                 "hard", ("networking", "scaling"),
                 ("Too many database indexes", "A surge of requests hitting a service simultaneously, e.g., after a cache miss or restart", "DNS propagation delay", "TCP connection timeout"), 1,
                 "Thundering herd occurs when many clients retry or request simultaneously, overwhelming a service. Mitigated with jitter, circuit breakers, or request coalescing."),
            quiz("net-11", "What is gRPC and when would you prefer it over REST?",
                 "hard", ("networking", "api"),
                 ("gRPC is a text-based protocol for browsers", "gRPC uses Protocol Buffers over HTTP/2 for high-performance inter-service communication", "gRPC replaces WebSockets", "gRPC is only for streaming"), 1,
                 "gRPC offers binary serialization, multiplexing, and streaming — ideal for internal microservice calls where browser compatibility isn't needed."),
            quiz("net-12", "What problem does connection pooling solve?",
                 "medium", ("networking", "performance"),
                 ("DNS resolution latency", "The overhead of repeatedly creating and destroying TCP connections", "SSL certificate management", "Load balancer failover"), 1,
                 "Connection pools reuse existing connections, avoiding the cost of TCP handshakes and TLS negotiation per request."),
            quiz("net-13", "In a microservices architecture, what is service discovery?",
                 "medium", ("networking", "microservices"),
                 ("Finding bugs in services", "A mechanism for services to find each other's network locations dynamically", "A load balancing algorithm", "A caching strategy"), 1,
                 "Service discovery (e.g., Consul, Kubernetes DNS) allows services to locate each other without hardcoded addresses."),
            quiz("net-14", "What is the purpose of a health check endpoint in a distributed system?",
                 "easy", ("networking", "observability"),
                 ("To encrypt traffic", "To allow load balancers and orchestrators to determine if a service instance is healthy", "To reset connections", "To cache responses"), 1,
                 "Health checks let infrastructure route traffic away from unhealthy instances automatically."),
            quiz("net-15", "What is HTTP long polling?",
                 "medium", ("networking", "real-time"),
                 ("A client sends requests every second", "The server holds the request open until new data is available, then responds", "A type of WebSocket", "A caching technique"), 1,
                 "Long polling simulates server push: the server delays responding until it has new data, then the client immediately re-requests."),
            quiz("net-16", "What is the TCP three-way handshake?",
                 "medium", ("networking", "tcp"),
                 ("GET → POST → PUT", "SYN → SYN-ACK → ACK", "CONNECT → ACCEPT → CLOSE", "REQUEST → RESPONSE → CONFIRM"), 1,
                 "TCP connections begin with SYN from client, SYN-ACK from server, ACK from client."),
            quiz("net-17", "Why is HTTP/2 preferred for modern APIs over HTTP/1.1?",
                 "hard", ("networking", "http"),
                 ("HTTP/2 uses XML instead of JSON", "HTTP/2 supports multiplexing multiple requests over a single connection, header compression, and server push", "HTTP/2 is simpler to implement", "HTTP/2 doesn't need TLS"), 1,
                 "HTTP/2 eliminates head-of-line blocking at the application layer with multiplexed streams."),
            quiz("net-18", "What is a circuit breaker pattern in distributed systems?",
                 "hard", ("networking", "resilience"),
                 ("A hardware component in servers", "A pattern that stops calling a failing service after a threshold, preventing cascade failures", "A type of load balancer", "A database isolation level"), 1,
                 "Circuit breakers trip after N failures, returning errors immediately instead of waiting on a dead service. After a cooldown, they allow test requests."),
            quiz("net-19", "What is the difference between horizontal and vertical scaling?",
                 "easy", ("networking", "scaling"),
                 ("Horizontal is cheaper", "Horizontal adds more machines; vertical upgrades the existing machine's resources", "Vertical is always better", "They are the same"), 1,
                 "Horizontal scaling (scale out) adds nodes; vertical scaling (scale up) adds CPU/RAM to one node."),
            quiz("net-20", "What is anycast routing and where is it commonly used?",
                 "hard", ("networking", "dns"),
                 ("Routing to all servers simultaneously", "Routing to the nearest server sharing the same IP address, commonly used by CDNs and DNS", "A multicast alternative", "A load balancing algorithm"), 1,
                 "Anycast routes traffic to the topologically nearest node, used by CDNs (Cloudflare) and DNS root servers."),
        ),
    )


def api_design_lesson() -> Lesson:
    return Lesson(
        id="hld-api-design", number=101, title="API Design",
        focus=("REST", "GraphQL", "gRPC", "idempotency", "versioning"),
        overview="API design is critical in interviews — you'll be asked to define endpoints, choose protocols, and handle edge cases.",
        patterns=(), badge="HLD",
        tasks=(
            quiz("api-1", "What makes an API call idempotent?",
                 "medium", ("api", "idempotency"),
                 ("It always succeeds", "Making the same call multiple times produces the same result as making it once", "It returns data faster", "It uses caching"), 1,
                 "Idempotency ensures retries are safe. PUT and DELETE are naturally idempotent; POST typically isn't."),
            quiz("api-2", "Which HTTP methods are idempotent?",
                 "medium", ("api", "http"),
                 ("Only GET", "GET, PUT, DELETE", "POST, PATCH", "All methods"), 1,
                 "GET (safe), PUT, DELETE are idempotent. POST creates new resources each time. PATCH may or may not be."),
            quiz("api-3", "When would you choose GraphQL over REST?",
                 "medium", ("api", "graphql"),
                 ("When you need maximum simplicity", "When clients need flexible queries and want to avoid over/under-fetching", "When you need file uploads", "When you have a single client"), 1,
                 "GraphQL lets clients request exactly the fields they need, reducing payload size and round trips."),
            quiz("api-4", "What is the N+1 query problem in API design?",
                 "hard", ("api", "performance"),
                 ("Making N+1 API calls instead of batching", "Fetching a list (1 query) then fetching related data for each item (N queries)", "Having too many endpoints", "Using N+1 HTTP methods"), 1,
                 "The N+1 problem kills performance. Solutions: batching, DataLoader pattern, or eager loading with JOINs."),
            quiz("api-5", "What is API rate limiting and why is it important?",
                 "medium", ("api", "rate-limiting"),
                 ("It speeds up responses", "It restricts the number of requests a client can make in a time window to prevent abuse", "It encrypts traffic", "It replaces authentication"), 1,
                 "Rate limiting protects services from abuse, ensures fair usage, and prevents cascade failures."),
            quiz("api-6", "What is the difference between authentication and authorization?",
                 "easy", ("api", "security"),
                 ("They are the same thing", "Authentication verifies identity; authorization determines what the identity can access", "Authentication is for APIs; authorization is for databases", "Authorization comes before authentication"), 1,
                 "AuthN (who are you?) comes before AuthZ (what are you allowed to do?)."),
            quiz("api-7", "What is an idempotency key and when do you use it?",
                 "hard", ("api", "idempotency"),
                 ("A database primary key", "A unique client-generated token sent with requests to prevent duplicate processing on retries", "An API version number", "A session token"), 1,
                 "Idempotency keys (e.g., Stripe's) let servers detect and deduplicate retried requests, critical for payment systems."),
            quiz("api-8", "What is pagination and why is it important for APIs?",
                 "easy", ("api", "pagination"),
                 ("Sorting results", "Breaking large result sets into smaller pages to reduce response size and server load", "Encrypting responses", "Caching queries"), 1,
                 "Without pagination, a query returning millions of rows would crash clients and overwhelm servers."),
            quiz("api-9", "What is the difference between cursor-based and offset-based pagination?",
                 "hard", ("api", "pagination"),
                 ("They are identical", "Offset skips N rows (fragile with inserts); cursor uses an opaque pointer to the last item (stable)", "Cursor is slower", "Offset is more accurate"), 1,
                 "Cursor pagination avoids the 'shifting window' problem when data changes between pages."),
            quiz("api-10", "How should you handle API versioning?",
                 "medium", ("api", "versioning"),
                 ("Never version APIs", "Use URL path (/v1/), query params, or Accept headers to version your API", "Change the domain name", "Use different ports"), 1,
                 "URL path versioning (/v1/) is most common and visible. Header versioning is cleaner but less discoverable."),
            quiz("api-11", "What HTTP status code indicates a successful resource creation?",
                 "easy", ("api", "http"),
                 ("200 OK", "201 Created", "204 No Content", "301 Redirect"), 1,
                 "201 Created is the standard response for successful POST requests that create a resource."),
            quiz("api-12", "What is the purpose of HATEOAS in REST?",
                 "hard", ("api", "rest"),
                 ("Faster responses", "Including links in responses so clients can discover available actions dynamically", "A caching mechanism", "Error handling"), 1,
                 "HATEOAS makes APIs self-documenting by embedding navigation links, though it's rarely used in practice."),
            quiz("api-13", "In a system design interview, when would you use webhooks?",
                 "medium", ("api", "webhooks"),
                 ("For database queries", "When the server needs to notify external clients about events asynchronously", "For authentication", "For file storage"), 1,
                 "Webhooks push event notifications to registered URLs — used by Stripe, GitHub, Slack for event-driven integrations."),
            quiz("api-14", "What is the difference between synchronous and asynchronous API calls?",
                 "medium", ("api", "async"),
                 ("Sync is always faster", "Sync blocks until response; async returns immediately with a job ID for later polling", "Async doesn't return responses", "They use different HTTP methods"), 1,
                 "Async APIs return 202 Accepted with a job/task ID. The client polls or gets a webhook callback for the result."),
            quiz("api-15", "What is API gateway and what problems does it solve?",
                 "medium", ("api", "gateway"),
                 ("A database proxy", "A single entry point that handles routing, auth, rate limiting, and protocol translation for microservices", "A CDN", "A message queue"), 1,
                 "API gateways (Kong, AWS API Gateway) centralize cross-cutting concerns and simplify client-to-microservice communication."),
            quiz("api-16", "What is a 429 status code?",
                 "medium", ("api", "rate-limiting"),
                 ("Server Error", "Too Many Requests — the client has been rate limited", "Not Found", "Unauthorized"), 1,
                 "429 tells the client to slow down. Usually includes a Retry-After header."),
            quiz("api-17", "What is the difference between PUT and PATCH?",
                 "medium", ("api", "http"),
                 ("No difference", "PUT replaces the entire resource; PATCH applies a partial update", "PATCH is faster", "PUT is for creation only"), 1,
                 "PUT requires sending the full resource representation; PATCH sends only the changed fields."),
            quiz("api-18", "Why is it bad practice to use GET requests for operations that modify data?",
                 "medium", ("api", "rest"),
                 ("GET is slower", "GET requests can be cached, bookmarked, and retried by browsers/proxies, causing unintended mutations", "GET can't send JSON", "GET has size limits"), 1,
                 "GET is defined as safe and idempotent — caches, crawlers, and prefetchers may replay them unexpectedly."),
            quiz("api-19", "What is content negotiation in REST APIs?",
                 "hard", ("api", "rest"),
                 ("Negotiating API pricing", "Using Accept/Content-Type headers to agree on response format (JSON, XML, Protobuf)", "A rate limiting strategy", "A versioning approach"), 1,
                 "Content negotiation lets clients and servers agree on the data format via HTTP headers."),
            quiz("api-20", "What is back-pressure in API design?",
                 "hard", ("api", "resilience"),
                 ("A compression technique", "A mechanism where a service signals upstream that it's overwhelmed and requests should slow down", "A caching strategy", "A type of load balancer"), 1,
                 "Back-pressure prevents cascade failures by propagating overload signals upstream. Common in streaming systems."),
        ),
    )


def data_modeling_lesson() -> Lesson:
    return Lesson(
        id="hld-data-modeling", number=102, title="Data Modeling & Databases",
        focus=("SQL vs NoSQL", "normalization", "denormalization", "partitioning", "replication"),
        overview="Choosing the right data model and database is the backbone of every system design. Know the tradeoffs.",
        patterns=(), badge="HLD",
        tasks=(
            quiz("dm-1", "When would you choose a NoSQL document store over a relational database?",
                 "medium", ("data-modeling", "nosql"),
                 ("Always, NoSQL is newer", "When the schema varies significantly across records and you need horizontal scalability", "When you need strong ACID transactions", "When data is highly relational"), 1,
                 "Document stores excel at flexible schemas and horizontal scaling, but sacrifice JOINs and strong consistency."),
            quiz("dm-2", "What is database normalization?",
                 "easy", ("data-modeling", "normalization"),
                 ("Making data bigger", "Organizing data to reduce redundancy by splitting into related tables", "Encrypting data", "Indexing all columns"), 1,
                 "Normalization (1NF → 2NF → 3NF) eliminates data redundancy, improving consistency at the cost of JOIN complexity."),
            quiz("dm-3", "When is denormalization the right choice?",
                 "medium", ("data-modeling", "denormalization"),
                 ("Always in production", "When read performance matters more than write consistency, and you can tolerate data duplication", "When data is small", "When using NoSQL"), 1,
                 "Denormalization precomputes JOINs into a single table/document, trading storage and write complexity for read speed."),
            quiz("dm-4", "What is the difference between horizontal and vertical database partitioning?",
                 "medium", ("data-modeling", "partitioning"),
                 ("They are the same", "Horizontal splits rows across shards; vertical splits columns across tables", "Horizontal is for SQL; vertical for NoSQL", "Vertical adds replicas"), 1,
                 "Horizontal partitioning (sharding) distributes rows; vertical partitioning separates columns into different tables."),
            quiz("dm-5", "What is database replication and why is it used?",
                 "easy", ("data-modeling", "replication"),
                 ("Moving data to a new database", "Copying data across multiple nodes for fault tolerance and read scalability", "Backing up once per day", "Encrypting data at rest"), 1,
                 "Replication ensures availability if one node fails and allows distributing read queries across replicas."),
            quiz("dm-6", "What is the difference between leader-follower and multi-leader replication?",
                 "hard", ("data-modeling", "replication"),
                 ("No difference", "Leader-follower has one write node; multi-leader allows writes to multiple nodes with conflict resolution", "Multi-leader is slower", "Leader-follower doesn't replicate"), 1,
                 "Multi-leader improves write availability (e.g., multi-region) but introduces write conflicts that need resolution strategies."),
            quiz("dm-7", "What is eventual consistency?",
                 "medium", ("data-modeling", "consistency"),
                 ("Data is never consistent", "All replicas will converge to the same state given enough time without new writes", "Reads always return latest write", "A database error state"), 1,
                 "Eventual consistency trades immediate consistency for availability and partition tolerance (AP in CAP)."),
            quiz("dm-8", "When would you use a column-family store like Cassandra?",
                 "hard", ("data-modeling", "nosql"),
                 ("For complex JOINs", "For high write throughput with predictable query patterns and horizontal scalability", "For small datasets", "For ACID transactions"), 1,
                 "Cassandra excels at write-heavy workloads with known access patterns, like time-series data or activity feeds."),
            quiz("dm-9", "What is a write-ahead log (WAL)?",
                 "hard", ("data-modeling", "internals"),
                 ("A backup schedule", "A log where changes are recorded before being applied to the database, ensuring durability and crash recovery", "A query optimizer", "An index type"), 1,
                 "WAL ensures durability: if the DB crashes after logging but before applying, it replays the log on restart."),
            quiz("dm-10", "What is the difference between OLTP and OLAP databases?",
                 "medium", ("data-modeling", "analytics"),
                 ("Same thing, different names", "OLTP handles transactional workloads (many small writes); OLAP handles analytical queries (large reads/aggregations)", "OLAP is faster for writes", "OLTP is for data warehousing"), 1,
                 "OLTP: operational systems (PostgreSQL). OLAP: analytics/reporting (BigQuery, Redshift, ClickHouse)."),
            quiz("dm-11", "What is a B-tree index and why is it the default for most databases?",
                 "hard", ("data-modeling", "indexing"),
                 ("A binary tree for caching", "A balanced tree structure that keeps data sorted, enabling O(log n) lookups, range queries, and ordered scans", "A hash function", "An in-memory structure"), 1,
                 "B-trees are the backbone of relational DB indexes — they support equality, range, and prefix queries efficiently."),
            quiz("dm-12", "When would you choose a hash index over a B-tree index?",
                 "hard", ("data-modeling", "indexing"),
                 ("Always, hash is faster", "When you only need exact-match lookups (no range queries) and want O(1) average performance", "When data is sorted", "For text search"), 1,
                 "Hash indexes are O(1) for point lookups but cannot support range queries, ORDER BY, or prefix matching."),
            quiz("dm-13", "What is a composite index and when is it useful?",
                 "medium", ("data-modeling", "indexing"),
                 ("An index on all columns", "An index on multiple columns, useful when queries filter on combinations of those columns", "A unique constraint", "A foreign key"), 1,
                 "Composite indexes follow the leftmost prefix rule: an index on (a, b, c) supports queries on (a), (a, b), and (a, b, c)."),
            quiz("dm-14", "What is a covering index?",
                 "hard", ("data-modeling", "indexing"),
                 ("An index that covers all tables", "An index that contains all columns needed for a query, eliminating the need to access the actual table", "A backup index", "An index on the primary key"), 1,
                 "Covering indexes avoid table lookups entirely, significantly improving read performance for specific queries."),
            quiz("dm-15", "What is the difference between strong consistency and linearizability?",
                 "hard", ("data-modeling", "consistency"),
                 ("They are the same", "Strong consistency ensures reads return the latest write; linearizability adds real-time ordering guarantees", "Linearizability is weaker", "Strong consistency only applies to SQL"), 1,
                 "Linearizability is the strongest guarantee: operations appear to execute atomically at some point between invocation and response."),
            quiz("dm-16", "What is a materialized view?",
                 "medium", ("data-modeling",),
                 ("A regular SQL view", "A precomputed query result stored as a table, periodically refreshed, trading freshness for read speed", "A type of index", "A cache layer"), 1,
                 "Materialized views precompute expensive JOINs/aggregations. Great for dashboards, but data may be stale."),
            quiz("dm-17", "What is the CAP theorem?",
                 "medium", ("data-modeling", "cap"),
                 ("Consistency, Availability, Performance — pick all three", "In a network partition, a distributed system must choose between Consistency and Availability", "A database optimization rule", "A caching strategy"), 1,
                 "CAP: during a partition (P), choose Consistency (CP — reject requests) or Availability (AP — serve potentially stale data). You can't have both."),
            quiz("dm-18", "What is a tombstone in distributed databases?",
                 "hard", ("data-modeling", "distributed"),
                 ("A crashed server", "A marker indicating a deleted record, used to propagate deletions across replicas before compaction removes it", "A backup mechanism", "An index entry"), 1,
                 "Tombstones prevent deleted data from being resurrected by replicas that haven't seen the delete yet."),
            quiz("dm-19", "What is the difference between optimistic and pessimistic locking?",
                 "hard", ("data-modeling", "concurrency"),
                 ("No difference", "Optimistic assumes no conflict and checks at commit; pessimistic locks upfront to prevent conflicts", "Optimistic is always better", "Pessimistic doesn't use locks"), 1,
                 "Optimistic locking (version numbers) works well with low contention. Pessimistic locking (SELECT FOR UPDATE) prevents conflicts but reduces throughput."),
            quiz("dm-20", "What is a time-series database optimized for?",
                 "medium", ("data-modeling", "timeseries"),
                 ("User profiles", "Append-heavy workloads with timestamp-ordered data like metrics, IoT, and financial data", "Graph traversals", "Full-text search"), 1,
                 "Time-series DBs (InfluxDB, TimescaleDB) optimize for high write throughput, time-range queries, and automatic data retention."),
        ),
    )
