"""Section-wise interview MCQ lessons for SQL practice."""
from __future__ import annotations
from .sql_practice import Task, Lesson

def _mcq(id, prompt, options, answer, explanation=""):
    return Task(id=id, prompt=prompt, starter="", solution="", kind="mcq",
                options=options, answer_index=answer, explanation=explanation)

BASIC_MCQS = Lesson("basic-mcq", 58, "Basic Queries: Interview MCQs", ["MCQ", "Interview"], [], [
    _mcq("bm-1", "What does SELECT * FROM employees do?",
         ["Deletes all rows", "Returns all columns and rows", "Creates a table", "Updates all rows"], 1,
         "SELECT * returns every column and every row from the table."),
    _mcq("bm-2", "Which clause filters rows BEFORE grouping?",
         ["HAVING", "WHERE", "ORDER BY", "GROUP BY"], 1,
         "WHERE filters individual rows before any GROUP BY is applied."),
    _mcq("bm-3", "What does DISTINCT do?",
         ["Sorts results", "Removes duplicate rows", "Counts rows", "Joins tables"], 1,
         "DISTINCT eliminates duplicate rows from the result set."),
    _mcq("bm-4", "Which operator checks for NULL values?",
         ["= NULL", "== NULL", "IS NULL", "EQUALS NULL"], 2,
         "NULL is not a value, so you must use IS NULL (not = NULL)."),
    _mcq("bm-5", "What does LIMIT 10 do?",
         ["Skips 10 rows", "Returns exactly 10 columns", "Returns at most 10 rows", "Filters rows > 10"], 2,
         "LIMIT restricts the maximum number of rows returned."),
    _mcq("bm-6", "Which is the correct order of SQL clauses?",
         ["SELECT, WHERE, FROM, ORDER BY", "SELECT, FROM, WHERE, ORDER BY", "FROM, SELECT, WHERE, ORDER BY", "SELECT, FROM, ORDER BY, WHERE"], 1,
         "The correct syntax order is SELECT ... FROM ... WHERE ... ORDER BY."),
    _mcq("bm-7", "What does ORDER BY price DESC do?",
         ["Sorts ascending", "Sorts descending by price", "Filters price", "Groups by price"], 1,
         "DESC sorts from highest to lowest value."),
    _mcq("bm-8", "How do you select only name and age columns?",
         ["SELECT name age", "SELECT name, age", "SELECT (name, age)", "GET name, age"], 1,
         "Columns are separated by commas in the SELECT clause."),
    _mcq("bm-9", "What does WHERE age BETWEEN 20 AND 30 return?",
         ["age > 20 AND age < 30", "age >= 20 AND age <= 30", "age = 20 OR age = 30", "age > 30"], 1,
         "BETWEEN is inclusive on both ends."),
    _mcq("bm-10", "Which keyword is used to rename a column in output?",
         ["RENAME", "AS", "LABEL", "SET"], 1,
         "AS creates an alias for a column or expression."),
    _mcq("bm-11", "What does WHERE name LIKE 'A%' match?",
         ["Names ending with A", "Names containing A", "Names starting with A", "Exact match 'A%'"], 2,
         "% is a wildcard; 'A%' matches strings starting with A."),
    _mcq("bm-12", "What does the _ wildcard match in LIKE?",
         ["Zero or more characters", "Exactly one character", "Any number", "Nothing"], 1,
         "The underscore matches exactly one character."),
    _mcq("bm-13", "What does WHERE status IN ('active', 'pending') do?",
         ["Checks substring", "Matches either value", "Joins tables", "Orders results"], 1,
         "IN checks if a value matches any value in the list."),
    _mcq("bm-14", "How do you sort by two columns?",
         ["ORDER BY a AND b", "ORDER BY a, b", "SORT BY a, b", "ORDER BY a + b"], 1,
         "Multiple sort columns are comma-separated in ORDER BY."),
    _mcq("bm-15", "What does SELECT 1 + 1 return?",
         ["Error", "11", "2", "1 + 1"], 2,
         "SQL evaluates arithmetic expressions; 1 + 1 = 2."),
    _mcq("bm-16", "Which statement is true about NULL?",
         ["NULL = NULL is TRUE", "NULL = NULL is FALSE", "NULL = NULL is NULL/UNKNOWN", "NULL equals 0"], 2,
         "Any comparison with NULL yields NULL/UNKNOWN, not TRUE or FALSE."),
    _mcq("bm-17", "What does OFFSET 5 do?",
         ["Returns 5 rows", "Skips the first 5 rows", "Limits to 5 columns", "Filters rows"], 1,
         "OFFSET skips a specified number of rows before returning results."),
    _mcq("bm-18", "Which is NOT a valid comparison operator?",
         ["<>", "!=", "=!", ">="], 2,
         "=! is not valid SQL syntax. Use <> or != for not-equal."),
    _mcq("bm-19", "What does WHERE NOT status = 'active' do?",
         ["Returns active rows", "Returns non-active rows", "Syntax error", "Deletes active rows"], 1,
         "NOT negates the condition, returning rows where status is not 'active'."),
    _mcq("bm-20", "How do you comment a single line in SQL?",
         ["// comment", "# comment", "-- comment", "/* comment"], 2,
         "SQL uses -- for single-line comments."),
])

JOINS_MCQS = Lesson("joins-mcq", 59, "Joins: Interview MCQs", ["MCQ", "Interview"], [], [
    _mcq("jm-1", "What does an INNER JOIN return?",
         ["All rows from both tables", "Only matching rows from both tables", "All from left, matching from right", "Cartesian product"], 1,
         "INNER JOIN returns only rows that have matching values in both tables."),
    _mcq("jm-2", "What does a LEFT JOIN return?",
         ["Only matching rows", "All from left table + matching from right", "All from right table + matching from left", "All from both"], 1,
         "LEFT JOIN keeps all rows from the left table, with NULLs for unmatched right rows."),
    _mcq("jm-3", "What is a CROSS JOIN?",
         ["Matches on a key", "Cartesian product of two tables", "Same as INNER JOIN", "Removes duplicates"], 1,
         "CROSS JOIN produces every combination of rows from both tables."),
    _mcq("jm-4", "If Table A has 3 rows and Table B has 4 rows, how many rows does a CROSS JOIN produce?",
         ["7", "12", "3", "4"], 1,
         "CROSS JOIN produces M × N rows: 3 × 4 = 12."),
    _mcq("jm-5", "What is a self join?",
         ["Joining a table with itself", "Joining without ON", "A type of CROSS JOIN", "Joining 3+ tables"], 0,
         "A self join joins a table to itself, typically using aliases."),
    _mcq("jm-6", "In LEFT JOIN, what value appears for unmatched right-side columns?",
         ["0", "Empty string", "NULL", "Error"], 2,
         "Unmatched columns from the right table are filled with NULL."),
    _mcq("jm-7", "What does a FULL OUTER JOIN return?",
         ["Only matching rows", "All from left only", "All rows from both tables, NULLs where no match", "Cartesian product"], 2,
         "FULL JOIN returns all rows from both tables, with NULLs for non-matching sides."),
    _mcq("jm-8", "Which finds rows in A with NO match in B?",
         ["A INNER JOIN B", "A LEFT JOIN B WHERE B.id IS NULL", "A CROSS JOIN B", "A RIGHT JOIN B"], 1,
         "LEFT JOIN + WHERE B.key IS NULL is the anti-join pattern."),
    _mcq("jm-9", "What does EXISTS do in a subquery?",
         ["Counts rows", "Returns TRUE if subquery returns any rows", "Joins tables", "Filters NULLs"], 1,
         "EXISTS returns TRUE if the correlated subquery produces at least one row."),
    _mcq("jm-10", "What is the difference between LEFT JOIN and LEFT OUTER JOIN?",
         ["LEFT OUTER JOIN includes NULLs", "No difference, they are the same", "LEFT JOIN is faster", "LEFT OUTER JOIN returns more rows"], 1,
         "They are identical; OUTER is optional syntax."),
    _mcq("jm-11", "Which join type is best for finding employees and their managers in one table?",
         ["INNER JOIN", "CROSS JOIN", "Self JOIN", "FULL JOIN"], 2,
         "A self join with aliases (e.g., e and m) links employees to their managers."),
    _mcq("jm-12", "What happens if you JOIN without an ON clause (not CROSS JOIN)?",
         ["Syntax error in most DBs", "Returns empty set", "Same as INNER JOIN", "Returns first table only"], 0,
         "Most SQL dialects require an ON clause for JOIN (except CROSS JOIN)."),
    _mcq("jm-13", "What is a semi-join?",
         ["Returns rows from A that have a match in B, without B's columns", "Returns all columns from both tables", "Same as INNER JOIN", "Returns unmatched rows"], 0,
         "A semi-join returns rows from the left table that have matches, typically via EXISTS or IN."),
    _mcq("jm-14", "Which is more efficient for large datasets: IN subquery or EXISTS?",
         ["IN is always faster", "EXISTS is generally better for correlated checks", "They are always identical", "Neither works on large data"], 1,
         "EXISTS can short-circuit; IN materializes the full subquery list."),
    _mcq("jm-15", "What does NOT EXISTS do?",
         ["Returns rows where subquery returns no rows", "Deletes unmatched rows", "Same as LEFT JOIN", "Counts non-matching rows"], 0,
         "NOT EXISTS returns rows from the outer query where the subquery finds no matches."),
    _mcq("jm-16", "Can you JOIN more than two tables in one query?",
         ["No, maximum is 2", "Yes, chain multiple JOINs", "Only with subqueries", "Only with UNION"], 1,
         "You can chain as many JOINs as needed in a single query."),
    _mcq("jm-17", "What is a natural join?",
         ["Joins on all columns with matching names", "Same as CROSS JOIN", "Joins without conditions", "A type of LEFT JOIN"], 0,
         "NATURAL JOIN automatically matches on columns with the same name in both tables."),
    _mcq("jm-18", "If two tables share a column name 'id', what must you do in a JOIN?",
         ["Nothing special", "Qualify with table name (e.g., t1.id)", "Rename one column", "Use DISTINCT"], 1,
         "Ambiguous column references must be qualified with table names or aliases."),
    _mcq("jm-19", "What does a RIGHT JOIN do differently from LEFT JOIN?",
         ["It keeps all rows from the RIGHT table instead of left", "It is faster", "It removes NULLs", "No difference"], 0,
         "RIGHT JOIN preserves all rows from the right table, the mirror of LEFT JOIN."),
    _mcq("jm-20", "What is an anti-join?",
         ["Returns rows from A that have NO match in B", "Returns all matches", "Same as CROSS JOIN", "Joins on inequality"], 0,
         "An anti-join returns rows from one table that do not have a corresponding match in another."),
])

EXPRESSIONS_MCQS = Lesson("expressions-mcq", 60, "Expressions & Types: Interview MCQs", ["MCQ", "Interview"], [], [
    _mcq("em-1", "What does COALESCE(a, b, c) return?",
         ["Always a", "The first non-NULL value", "The last value", "Sum of all"], 1,
         "COALESCE returns the first non-NULL argument in order."),
    _mcq("em-2", "What does CASE WHEN x > 10 THEN 'High' ELSE 'Low' END do?",
         ["Creates a column", "Conditionally returns 'High' or 'Low'", "Filters rows", "Joins tables"], 1,
         "CASE is SQL's if-then-else expression for conditional logic."),
    _mcq("em-3", "What does CAST('123' AS INTEGER) do?",
         ["Returns string '123'", "Converts string to integer 123", "Error", "Returns NULL"], 1,
         "CAST converts a value from one data type to another."),
    _mcq("em-4", "What does ROUND(3.456, 2) return?",
         ["3.45", "3.46", "3.5", "4"], 1,
         "ROUND rounds to the specified decimal places using standard rounding."),
    _mcq("em-5", "What does NULLIF(a, b) return?",
         ["NULL if a = b, otherwise a", "NULL if a is NULL", "Always NULL", "b if a = b"], 0,
         "NULLIF returns NULL when the two arguments are equal, otherwise the first argument."),
    _mcq("em-6", "What does LENGTH('Hello') return?",
         ["4", "5", "6", "Error"], 1,
         "LENGTH returns the number of characters in the string."),
    _mcq("em-7", "What does SUBSTR('Database', 1, 4) return?",
         ["Data", "atas", "base", "Dat"], 0,
         "SUBSTR extracts characters starting at position 1 for length 4."),
    _mcq("em-8", "What does REPLACE('Hello World', 'World', 'SQL') return?",
         ["Hello World", "Hello SQL", "SQL Hello", "Error"], 1,
         "REPLACE substitutes all occurrences of the search string."),
    _mcq("em-9", "What does TYPEOF(42) return in SQLite?",
         ["'number'", "'int'", "'integer'", "'real'"], 2,
         "SQLite's TYPEOF returns the storage class; 42 is 'integer'."),
    _mcq("em-10", "What is the result of 5 / 2 in integer arithmetic?",
         ["2.5", "2", "3", "Error"], 1,
         "Integer division truncates the decimal; 5 / 2 = 2."),
    _mcq("em-11", "How do you get a decimal result from 5 / 2?",
         ["5 / 2.0", "5 DIV 2", "DECIMAL(5/2)", "5 % 2"], 0,
         "Casting one operand to REAL (e.g., 5 / 2.0) forces float division."),
    _mcq("em-12", "What does strftime('%Y', '2024-03-15') return?",
         ["2024-03-15", "2024", "03", "15"], 1,
         "%Y extracts the four-digit year."),
    _mcq("em-13", "What does the || operator do in SQL?",
         ["Logical OR", "Concatenates strings", "Bitwise OR", "Division"], 1,
         "In SQLite and many databases, || concatenates strings."),
    _mcq("em-14", "What does ABS(-5) return?",
         ["-5", "5", "0", "Error"], 1,
         "ABS returns the absolute (non-negative) value."),
    _mcq("em-15", "What does TRIM('  hello  ') return?",
         ["  hello  ", "hello  ", "  hello", "hello"], 3,
         "TRIM removes leading and trailing whitespace."),
    _mcq("em-16", "What does UPPER('hello') return?",
         ["hello", "Hello", "HELLO", "hELLO"], 2,
         "UPPER converts all characters to uppercase."),
    _mcq("em-17", "What does julianday('2024-01-10') - julianday('2024-01-01') compute?",
         ["A date string", "Number of days between the dates (9)", "Seconds", "Error"], 1,
         "julianday returns a float day number; subtracting gives days between dates."),
    _mcq("em-18", "What does IFNULL(NULL, 'default') return?",
         ["NULL", "'default'", "Error", "0"], 1,
         "IFNULL returns the second argument if the first is NULL."),
    _mcq("em-19", "What does the modulo operator (%) do?",
         ["Division", "Returns the remainder", "Percentage", "Exponent"], 1,
         "% returns the remainder of integer division; 7 % 3 = 1."),
    _mcq("em-20", "What does INSTR('Hello World', 'World') return?",
         ["0", "5", "6", "7"], 3,
         "INSTR returns the 1-based position of the first occurrence; 'World' starts at position 7."),
])

MCQ_LESSONS = [BASIC_MCQS, JOINS_MCQS, EXPRESSIONS_MCQS]
