"""MCQ lessons batch 2: Aggregations, Sets, Advanced, DDL."""
from __future__ import annotations
from .sql_practice import Task, Lesson

def _mcq(id, prompt, options, answer, explanation=""):
    return Task(id=id, prompt=prompt, starter="", solution="", kind="mcq",
                options=options, answer_index=answer, explanation=explanation)

AGGREGATIONS_MCQS = Lesson("aggregations-mcq", 61, "Aggregations: Interview MCQs", ["MCQ", "Interview"], [], [
    _mcq("am-1", "What does COUNT(*) count?",
         ["Only non-NULL values", "All rows including NULLs", "Distinct values", "Columns"], 1,
         "COUNT(*) counts every row regardless of NULL values."),
    _mcq("am-2", "What does COUNT(column) count?",
         ["All rows", "Only non-NULL values in that column", "Distinct values", "NULL values"], 1,
         "COUNT(column) ignores NULL values in the specified column."),
    _mcq("am-3", "What is the difference between HAVING and WHERE?",
         ["No difference", "HAVING filters after GROUP BY, WHERE before", "WHERE is faster", "HAVING works without GROUP BY"], 1,
         "WHERE filters rows before grouping; HAVING filters groups after aggregation."),
    _mcq("am-4", "What does SUM(NULL) return?",
         ["0", "NULL", "Error", "Empty string"], 1,
         "Aggregate functions (except COUNT(*)) return NULL when all inputs are NULL."),
    _mcq("am-5", "What does AVG do with NULL values?",
         ["Treats them as 0", "Ignores them", "Returns error", "Counts them"], 1,
         "AVG ignores NULLs: it sums non-NULL values and divides by the count of non-NULLs."),
    _mcq("am-6", "Can you use a column alias in HAVING?",
         ["Yes, always", "Depends on the database", "No, never", "Only with subqueries"], 1,
         "Some databases (MySQL, SQLite) allow it; standard SQL and PostgreSQL do not."),
    _mcq("am-7", "What does GROUP BY do?",
         ["Sorts results", "Groups rows with same values for aggregation", "Filters rows", "Joins tables"], 1,
         "GROUP BY collapses rows with identical values into summary rows for aggregate functions."),
    _mcq("am-8", "Which is valid: SELECT name, COUNT(*) FROM t or SELECT name, COUNT(*) FROM t GROUP BY name?",
         ["Both are valid", "Only the first", "Only the second", "Neither"], 2,
         "Non-aggregated columns in SELECT must appear in GROUP BY."),
    _mcq("am-9", "What does COUNT(DISTINCT category) return?",
         ["Count of all rows", "Count of unique non-NULL category values", "Count of NULLs", "Error"], 1,
         "COUNT(DISTINCT col) counts the number of unique non-NULL values."),
    _mcq("am-10", "What does MIN return on an empty set?",
         ["0", "Empty string", "NULL", "Error"], 2,
         "Aggregate functions return NULL when applied to an empty set."),
    _mcq("am-11", "Can you nest aggregate functions like MAX(AVG(price))?",
         ["Yes, directly", "No, use a subquery or CTE", "Only in HAVING", "Only with GROUP BY"], 1,
         "You cannot nest aggregates; use a subquery to compute the inner aggregate first."),
    _mcq("am-12", "What does GROUP BY 1 mean?",
         ["Groups by the literal 1", "Groups by the first SELECT column", "Error", "Groups by all columns"], 1,
         "Positional notation: GROUP BY 1 refers to the first expression in SELECT."),
    _mcq("am-13", "What is the SQL execution order for SELECT with GROUP BY?",
         ["SELECT → FROM → WHERE → GROUP BY", "FROM → WHERE → GROUP BY → HAVING → SELECT", "SELECT → GROUP BY → WHERE → FROM", "GROUP BY → SELECT → FROM"], 1,
         "Logical order: FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY."),
    _mcq("am-14", "What does SUM(CASE WHEN status='active' THEN 1 ELSE 0 END) compute?",
         ["Total rows", "Count of active rows", "Sum of status values", "Error"], 1,
         "This is the conditional aggregation pattern: counting rows matching a condition."),
    _mcq("am-15", "Can HAVING be used without GROUP BY?",
         ["No, never", "Yes, it filters the single aggregate result", "Only in MySQL", "Error"], 1,
         "HAVING without GROUP BY treats the whole table as one group and filters the aggregate."),
    _mcq("am-16", "What does STRING_AGG / GROUP_CONCAT do?",
         ["Sums numbers", "Concatenates values from a group into a string", "Counts strings", "Splits strings"], 1,
         "GROUP_CONCAT (SQLite) / STRING_AGG (PostgreSQL) joins group values into a single string."),
    _mcq("am-17", "What is the difference between COUNT(*) and COUNT(1)?",
         ["COUNT(1) is faster", "COUNT(*) counts NULLs, COUNT(1) doesn't", "No practical difference", "COUNT(1) returns 1"], 2,
         "They are functionally identical; both count all rows."),
    _mcq("am-18", "Which aggregate function can be used to find the total of a column?",
         ["COUNT", "SUM", "AVG", "MAX"], 1,
         "SUM adds up all non-NULL values in the specified column."),
    _mcq("am-19", "What does HAVING COUNT(*) > 5 do?",
         ["Filters rows with value > 5", "Keeps only groups with more than 5 rows", "Limits to 5 results", "Orders by count"], 1,
         "HAVING filters groups; here it keeps only groups with more than 5 members."),
    _mcq("am-20", "Can you use WHERE with aggregate functions?",
         ["Yes", "No, use HAVING instead", "Only with subqueries in WHERE", "Only COUNT"], 2,
         "WHERE cannot reference aggregates directly. Use HAVING, or put the aggregate in a subquery."),
])

SETS_MCQS = Lesson("sets-mcq", 62, "Sets & Subqueries: Interview MCQs", ["MCQ", "Interview"], [], [
    _mcq("sm-1", "What does UNION do?",
         ["Joins tables side by side", "Combines results and removes duplicates", "Intersects results", "Cross joins"], 1,
         "UNION stacks result sets vertically and removes duplicate rows."),
    _mcq("sm-2", "What is the difference between UNION and UNION ALL?",
         ["No difference", "UNION ALL keeps duplicates, UNION removes them", "UNION ALL is slower", "UNION returns more rows"], 1,
         "UNION ALL keeps all rows including duplicates; UNION deduplicates."),
    _mcq("sm-3", "What does INTERSECT return?",
         ["All rows from both queries", "Only rows that appear in both result sets", "Rows unique to the first query", "Cartesian product"], 1,
         "INTERSECT returns only rows common to both queries."),
    _mcq("sm-4", "What does EXCEPT (or MINUS) return?",
         ["Rows in the first query but not in the second", "Rows in both queries", "All rows", "Difference of values"], 0,
         "EXCEPT returns rows from the first query that are not in the second query."),
    _mcq("sm-5", "What is required for UNION to work?",
         ["Same table names", "Same number of columns with compatible types", "Same WHERE clause", "Same ORDER BY"], 1,
         "All SELECT statements in a UNION must have the same number of columns with compatible types."),
    _mcq("sm-6", "What is a scalar subquery?",
         ["Returns multiple rows", "Returns exactly one value (one row, one column)", "Same as a CTE", "A correlated subquery"], 1,
         "A scalar subquery returns a single value and can be used anywhere an expression is expected."),
    _mcq("sm-7", "What is a correlated subquery?",
         ["A subquery that runs once", "A subquery that references the outer query's columns", "Same as JOIN", "A subquery with UNION"], 1,
         "A correlated subquery references columns from the outer query, executing once per outer row."),
    _mcq("sm-8", "Which is generally faster: IN with subquery or EXISTS?",
         ["IN is always faster", "EXISTS for large outer tables with selective subquery", "They are always equal", "Neither is fast"], 1,
         "EXISTS can short-circuit; performance depends on data distribution and indexing."),
    _mcq("sm-9", "Can a subquery be used in the FROM clause?",
         ["No", "Yes, as a derived table / inline view", "Only in PostgreSQL", "Only with UNION"], 1,
         "Subqueries in FROM create derived tables (also called inline views)."),
    _mcq("sm-10", "What does ANY/SOME do with a subquery?",
         ["Checks if all values match", "Returns TRUE if any value in the subquery satisfies the condition", "Same as IN", "Counts matches"], 1,
         "ANY returns TRUE if the comparison is true for at least one subquery value."),
    _mcq("sm-11", "What does ALL do with a subquery?",
         ["Same as ANY", "Returns TRUE only if ALL subquery values satisfy the condition", "Counts all rows", "Error"], 1,
         "ALL requires the condition to be true for every value returned by the subquery."),
    _mcq("sm-12", "Can you ORDER BY a UNION result?",
         ["No", "Yes, place ORDER BY after the last SELECT", "Only with UNION ALL", "Only by column index"], 1,
         "ORDER BY applies to the entire UNION result and goes after the final SELECT."),
    _mcq("sm-13", "Where can subqueries NOT be used?",
         ["SELECT clause", "WHERE clause", "GROUP BY clause", "FROM clause"], 2,
         "Subqueries cannot be used directly in the GROUP BY clause in standard SQL."),
    _mcq("sm-14", "What does WHERE price > (SELECT AVG(price) FROM products) find?",
         ["Products below average", "Products above average price", "The average price", "Error"], 1,
         "This compares each product's price against the scalar average of all products."),
    _mcq("sm-15", "What is a derived table?",
         ["A permanent table", "A subquery in the FROM clause", "A view", "A temporary table"], 1,
         "A derived table is a subquery used in the FROM clause, acting as an inline table."),
    _mcq("sm-16", "Can UNION combine more than two SELECTs?",
         ["No, only two", "Yes, chain multiple UNIONs", "Only with parentheses", "Only UNION ALL"], 1,
         "You can chain as many UNION (or UNION ALL) statements as needed."),
    _mcq("sm-17", "What does NOT IN (NULL, 1, 2) return?",
         ["Rows not equal to 1 or 2", "Always returns empty set", "Error", "Same as NOT IN (1, 2)"], 1,
         "If the list contains NULL, NOT IN returns no rows because x <> NULL is UNKNOWN."),
    _mcq("sm-18", "Which is a multi-row subquery operator?",
         ["=", ">", "IN", "LIKE"], 2,
         "IN can compare against multiple rows returned by a subquery."),
    _mcq("sm-19", "What happens if a scalar subquery returns more than one row?",
         ["Returns the first row", "Error", "Returns NULL", "Returns all rows"], 1,
         "A scalar subquery must return at most one row; otherwise it raises an error."),
    _mcq("sm-20", "What is the key advantage of EXISTS over IN?",
         ["Simpler syntax", "Handles NULLs correctly and can short-circuit", "Returns more rows", "Faster sorting"], 1,
         "EXISTS doesn't have the NULL pitfall of NOT IN and stops as soon as it finds a match."),
])

ADVANCED_MCQS = Lesson("advanced-mcq", 63, "Advanced Queries: Interview MCQs", ["MCQ", "Interview"], [], [
    _mcq("adm-1", "What is a CTE?",
         ["A permanent table", "A Common Table Expression defined with WITH", "A type of JOIN", "A stored procedure"], 1,
         "CTEs provide named temporary result sets using the WITH clause."),
    _mcq("adm-2", "What does ROW_NUMBER() do?",
         ["Counts total rows", "Assigns a unique sequential number to each row in a partition", "Ranks with ties", "Generates random numbers"], 1,
         "ROW_NUMBER assigns 1, 2, 3... without gaps or ties within each partition."),
    _mcq("adm-3", "What is the difference between RANK() and DENSE_RANK()?",
         ["No difference", "RANK leaves gaps after ties, DENSE_RANK does not", "DENSE_RANK is slower", "RANK doesn't handle ties"], 1,
         "With values 10,10,20: RANK gives 1,1,3; DENSE_RANK gives 1,1,2."),
    _mcq("adm-4", "What does PARTITION BY do in a window function?",
         ["Groups rows for aggregation", "Divides rows into partitions for separate window calculations", "Sorts rows", "Filters partitions"], 1,
         "PARTITION BY creates subsets of data; the window function operates independently on each."),
    _mcq("adm-5", "What does LAG(column, 1) return?",
         ["The next row's value", "The previous row's value", "The current value", "NULL always"], 1,
         "LAG accesses a previous row's value within the same partition."),
    _mcq("adm-6", "What does LEAD(column, 1) return?",
         ["The previous row's value", "The next row's value", "The first value", "The last value"], 1,
         "LEAD accesses a subsequent row's value within the same partition."),
    _mcq("adm-7", "Can a CTE reference itself?",
         ["No, never", "Yes, that's a recursive CTE", "Only in PostgreSQL", "Only with UNION ALL"], 1,
         "A recursive CTE references itself and must use UNION ALL with a base case and recursive step."),
    _mcq("adm-8", "What does NTILE(4) do?",
         ["Returns top 4 rows", "Divides rows into 4 roughly equal buckets", "Multiplies by 4", "Groups into quartiles alphabetically"], 1,
         "NTILE(n) distributes rows into n approximately equal-sized groups."),
    _mcq("adm-9", "What does SUM() OVER (ORDER BY date) compute?",
         ["Total sum", "Running/cumulative sum", "Average", "Count"], 1,
         "SUM with ORDER BY in the OVER clause computes a running total."),
    _mcq("adm-10", "What is the default frame for a window function with ORDER BY?",
         ["ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING", "RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW", "ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING", "No frame"], 1,
         "The default frame with ORDER BY is RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW."),
    _mcq("adm-11", "Can you use WHERE to filter window function results?",
         ["Yes, directly", "No, use a subquery or CTE to filter", "Only with HAVING", "Only ROW_NUMBER"], 1,
         "Window functions execute after WHERE; to filter by their result, wrap in a subquery."),
    _mcq("adm-12", "What is the top-N per group pattern?",
         ["GROUP BY with LIMIT", "ROW_NUMBER() PARTITION BY group ORDER BY col, then filter rn <= N", "CROSS JOIN with LIMIT", "UNION of LIMITs"], 1,
         "Assign ROW_NUMBER within each group, then filter in an outer query."),
    _mcq("adm-13", "A recursive CTE must have which two parts?",
         ["SELECT and INSERT", "Base case (anchor) and recursive step", "CTE and subquery", "JOIN and WHERE"], 1,
         "Recursive CTEs need an anchor member (base case) UNION ALL'd with the recursive member."),
    _mcq("adm-14", "What does FIRST_VALUE(col) OVER (...) return?",
         ["The last value", "The first value in the window frame", "The minimum", "NULL"], 1,
         "FIRST_VALUE returns the first value in the ordered window frame."),
    _mcq("adm-15", "Can you have multiple CTEs in one WITH clause?",
         ["No, only one", "Yes, separate them with commas", "Only with RECURSIVE", "Only two"], 1,
         "Multiple CTEs are comma-separated: WITH cte1 AS (...), cte2 AS (...) SELECT ..."),
    _mcq("adm-16", "What does ROWS BETWEEN 2 PRECEDING AND CURRENT ROW define?",
         ["A 2-row window before and after", "A 3-row sliding window", "All preceding rows", "Only current row"], 1,
         "This frame includes the current row plus the 2 rows before it (3 rows total)."),
    _mcq("adm-17", "Can a CTE be used in UPDATE or DELETE statements?",
         ["No, only SELECT", "Yes, in most modern databases", "Only in PostgreSQL", "Only with temp tables"], 1,
         "CTEs can be used with SELECT, INSERT, UPDATE, and DELETE in modern SQL."),
    _mcq("adm-18", "What does PERCENT_RANK() compute?",
         ["Absolute rank", "Relative rank as (rank-1)/(total_rows-1)", "Percentile value", "Random percentage"], 1,
         "PERCENT_RANK gives the relative position of a row as a fraction between 0 and 1."),
    _mcq("adm-19", "How do you find the moving average of the last 3 rows?",
         ["AVG(col) GROUP BY 3", "AVG(col) OVER (ORDER BY date ROWS BETWEEN 2 PRECEDING AND CURRENT ROW)", "AVG(col) LIMIT 3", "AVG(col) HAVING count = 3"], 1,
         "Use a window frame with ROWS BETWEEN 2 PRECEDING AND CURRENT ROW for a 3-row window."),
    _mcq("adm-20", "What happens if a recursive CTE has no termination condition?",
         ["Returns empty set", "Infinite loop (DB may have a recursion limit)", "Error at parse time", "Returns NULL"], 1,
         "Without a termination condition, the CTE recurses until the DB's recursion limit is hit."),
])

DDL_MCQS = Lesson("ddl-mcq", 64, "DDL & Admin: Interview MCQs", ["MCQ", "Interview"], [], [
    _mcq("dm-1", "What does DDL stand for?",
         ["Data Definition Language", "Data Deletion Language", "Database Design Logic", "Dynamic Data Linking"], 0,
         "DDL = Data Definition Language — commands that define/alter database structure."),
    _mcq("dm-2", "Which is a DDL command?",
         ["SELECT", "INSERT", "CREATE TABLE", "UPDATE"], 2,
         "CREATE TABLE defines structure; SELECT/INSERT/UPDATE are DML."),
    _mcq("dm-3", "What does DROP TABLE do?",
         ["Deletes all rows", "Removes the entire table including structure", "Truncates data", "Renames table"], 1,
         "DROP TABLE permanently removes the table and all its data."),
    _mcq("dm-4", "What is the difference between DELETE and TRUNCATE?",
         ["No difference", "DELETE is row-by-row with WHERE support; TRUNCATE removes all rows at once", "TRUNCATE is slower", "DELETE cannot have WHERE"], 1,
         "DELETE supports WHERE and logs each row; TRUNCATE is faster but removes all rows."),
    _mcq("dm-5", "What does ALTER TABLE ... ADD COLUMN do?",
         ["Removes a column", "Adds a new column to an existing table", "Creates a new table", "Modifies data"], 1,
         "ADD COLUMN extends an existing table's schema with a new column."),
    _mcq("dm-6", "What is a PRIMARY KEY?",
         ["Any column", "A unique, non-NULL identifier for each row", "A foreign reference", "An index only"], 1,
         "PRIMARY KEY uniquely identifies each row and cannot contain NULL."),
    _mcq("dm-7", "What does a FOREIGN KEY enforce?",
         ["Uniqueness", "Referential integrity between tables", "NOT NULL", "Sorting"], 1,
         "FOREIGN KEY ensures values in a column match values in another table's primary key."),
    _mcq("dm-8", "What does ON DELETE CASCADE do?",
         ["Prevents deletion", "Automatically deletes child rows when parent is deleted", "Sets to NULL", "Logs deletion"], 1,
         "CASCADE automatically deletes dependent rows when the referenced row is deleted."),
    _mcq("dm-9", "What is a CHECK constraint?",
         ["Validates data against a condition before insert/update", "Checks for NULL", "Same as UNIQUE", "A type of index"], 0,
         "CHECK ensures that values satisfy a Boolean expression (e.g., price >= 0)."),
    _mcq("dm-10", "What is a UNIQUE constraint?",
         ["Same as PRIMARY KEY", "Ensures all values in a column are different (allows one NULL)", "A type of JOIN", "An index"], 1,
         "UNIQUE prevents duplicate values; unlike PRIMARY KEY, it allows NULL (typically one)."),
    _mcq("dm-11", "What does CREATE INDEX do?",
         ["Creates a table", "Creates a data structure to speed up queries", "Creates a view", "Sorts the table"], 1,
         "An index is a data structure (like B-tree) that speeds up lookups on the indexed columns."),
    _mcq("dm-12", "What is a VIEW?",
         ["A copy of a table", "A saved SQL query that acts like a virtual table", "A temporary table", "An index"], 1,
         "A VIEW stores a query definition; when queried, it executes the underlying SQL."),
    _mcq("dm-13", "What is SQL injection?",
         ["A type of JOIN", "Malicious SQL inserted via user input to manipulate queries", "A data type", "A stored procedure"], 1,
         "SQL injection exploits unparameterized queries to execute unauthorized SQL."),
    _mcq("dm-14", "How do you prevent SQL injection?",
         ["Use LIKE", "Use parameterized queries / prepared statements", "Use DISTINCT", "Use VARCHAR"], 1,
         "Parameterized queries separate SQL logic from data, preventing injection."),
    _mcq("dm-15", "What does DEFAULT do in a column definition?",
         ["Makes it primary key", "Sets a value used when no value is provided on INSERT", "Makes it NOT NULL", "Creates an index"], 1,
         "DEFAULT provides a fallback value when INSERT doesn't specify one for that column."),
    _mcq("dm-16", "What is a composite primary key?",
         ["A key with auto-increment", "A primary key consisting of two or more columns", "A foreign key", "A unique index"], 1,
         "A composite key uses multiple columns together as the unique identifier."),
    _mcq("dm-17", "What does AUTOINCREMENT do?",
         ["Creates an index", "Automatically generates a unique incrementing integer for each new row", "Makes column NOT NULL", "Sorts automatically"], 1,
         "AUTOINCREMENT ensures the ID is always greater than any previously used value."),
    _mcq("dm-18", "What is the difference between DROP and ALTER TABLE DROP COLUMN?",
         ["No difference", "DROP removes the table; ALTER TABLE DROP COLUMN removes one column", "DROP is faster", "ALTER is for data"], 1,
         "DROP TABLE removes the entire table; ALTER TABLE DROP COLUMN removes a specific column."),
    _mcq("dm-19", "What does INSERT INTO ... SELECT do?",
         ["Creates a table", "Inserts rows into a table from another query's results", "Updates rows", "Deletes and re-inserts"], 1,
         "INSERT INTO ... SELECT copies data from one query result into an existing table."),
    _mcq("dm-20", "What is the difference between a clustered and non-clustered index?",
         ["No difference", "Clustered sorts the actual table data; non-clustered is a separate structure", "Non-clustered is faster", "Clustered is only for primary keys"], 1,
         "A clustered index determines the physical order of data; a table can have only one."),
])

MCQ_LESSONS_2 = [AGGREGATIONS_MCQS, SETS_MCQS, ADVANCED_MCQS, DDL_MCQS]
