"""MCQ lessons batch 2: Aggregations, Sets, Advanced, DDL."""
from __future__ import annotations
from .sql_practice import Task, Lesson

def _mcq(id, prompt, options, answer, explanation=""):
    return Task(id=id, prompt=prompt, starter="", solution="", kind="mcq",
                options=options, answer_index=answer, explanation=explanation)

AGGREGATIONS_MCQS = Lesson("aggregations-mcq", 69, "Aggregations: Interview MCQs", ["MCQ", "Interview"], [], [
    _mcq("am-1", "What does COUNT(*) count?",
         ["Distinct values", "Only non-NULL values", "Columns", "All rows including NULLs"], 3,
         "COUNT(*) counts every row regardless of NULL values."),
    _mcq("am-2", "What does COUNT(column) count?",
         ["Distinct values", "All rows", "NULL values", "Only non-NULL values in that column"], 3,
         "COUNT(column) ignores NULL values in the specified column."),
    _mcq("am-3", "What is the difference between HAVING and WHERE?",
         ["WHERE is faster", "HAVING filters after GROUP BY, WHERE before", "No difference", "HAVING works without GROUP BY"], 1,
         "WHERE filters rows before grouping; HAVING filters groups after aggregation."),
    _mcq("am-4", "What does SUM(NULL) return?",
         ["Error", "NULL", "0", "Empty string"], 1,
         "Aggregate functions (except COUNT(*)) return NULL when all inputs are NULL."),
    _mcq("am-5", "What does AVG do with NULL values?",
         ["Returns error", "Counts them", "Treats them as 0", "Ignores them"], 3,
         "AVG ignores NULLs: it sums non-NULL values and divides by the count of non-NULLs."),
    _mcq("am-6", "Can you use a column alias in HAVING?",
         ["Yes, always", "Only with subqueries", "No, never", "Depends on the database"], 3,
         "Some databases (MySQL, SQLite) allow it; standard SQL and PostgreSQL do not."),
    _mcq("am-7", "What does GROUP BY do?",
         ["Joins tables", "Filters rows", "Groups rows with same values for aggregation", "Sorts results"], 2,
         "GROUP BY collapses rows with identical values into summary rows for aggregate functions."),
    _mcq("am-8", "Which is valid: SELECT name, COUNT(*) FROM t or SELECT name, COUNT(*) FROM t GROUP BY name?",
         ["Neither", "Only the second", "Only the first", "Both are valid"], 1,
         "Non-aggregated columns in SELECT must appear in GROUP BY."),
    _mcq("am-9", "What does COUNT(DISTINCT category) return?",
         ["Count of all rows", "Error", "Count of NULLs", "Count of unique non-NULL category values"], 3,
         "COUNT(DISTINCT col) counts the number of unique non-NULL values."),
    _mcq("am-10", "What does MIN return on an empty set?",
         ["0", "Error", "Empty string", "NULL"], 3,
         "Aggregate functions return NULL when applied to an empty set."),
    _mcq("am-11", "Can you nest aggregate functions like MAX(AVG(price))?",
         ["Only with GROUP BY", "Only in HAVING", "Yes, directly", "No, use a subquery or CTE"], 3,
         "You cannot nest aggregates; use a subquery to compute the inner aggregate first."),
    _mcq("am-12", "What does GROUP BY 1 mean?",
         ["Groups by all columns", "Groups by the literal 1", "Groups by the first SELECT column", "Error"], 2,
         "Positional notation: GROUP BY 1 refers to the first expression in SELECT."),
    _mcq("am-13", "What is the SQL execution order for SELECT with GROUP BY?",
         ["SELECT → GROUP BY → WHERE → FROM", "FROM → WHERE → GROUP BY → HAVING → SELECT", "GROUP BY → SELECT → FROM", "SELECT → FROM → WHERE → GROUP BY"], 1,
         "Logical order: FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY."),
    _mcq("am-14", "What does SUM(CASE WHEN status='active' THEN 1 ELSE 0 END) compute?",
         ["Sum of status values", "Error", "Total rows", "Count of active rows"], 3,
         "This is the conditional aggregation pattern: counting rows matching a condition."),
    _mcq("am-15", "Can HAVING be used without GROUP BY?",
         ["No, never", "Only in MySQL", "Error", "Yes, it filters the single aggregate result"], 3,
         "HAVING without GROUP BY treats the whole table as one group and filters the aggregate."),
    _mcq("am-16", "What does STRING_AGG / GROUP_CONCAT do?",
         ["Concatenates values from a group into a string", "Counts strings", "Sums numbers", "Splits strings"], 0,
         "GROUP_CONCAT (SQLite) / STRING_AGG (PostgreSQL) joins group values into a single string."),
    _mcq("am-17", "What is the difference between COUNT(*) and COUNT(1)?",
         ["COUNT(1) returns 1", "COUNT(1) is faster", "No practical difference", "COUNT(*) counts NULLs, COUNT(1) doesn't"], 2,
         "They are functionally identical; both count all rows."),
    _mcq("am-18", "Which aggregate function can be used to find the total of a column?",
         ["SUM", "AVG", "COUNT", "MAX"], 0,
         "SUM adds up all non-NULL values in the specified column."),
    _mcq("am-19", "What does HAVING COUNT(*) > 5 do?",
         ["Filters rows with value > 5", "Keeps only groups with more than 5 rows", "Limits to 5 results", "Orders by count"], 1,
         "HAVING filters groups; here it keeps only groups with more than 5 members."),
    _mcq("am-20", "Can you use WHERE with aggregate functions?",
         ["Yes", "No, use HAVING instead", "Only with subqueries in WHERE", "Only COUNT"], 2,
         "WHERE cannot reference aggregates directly. Use HAVING, or put the aggregate in a subquery."),
])

SETS_MCQS = Lesson("sets-mcq", 70, "Sets & Subqueries: Interview MCQs", ["MCQ", "Interview"], [], [
    _mcq("sm-1", "What does UNION do?",
         ["Combines results and removes duplicates", "Intersects results", "Joins tables side by side", "Cross joins"], 0,
         "UNION stacks result sets vertically and removes duplicate rows."),
    _mcq("sm-2", "What is the difference between UNION and UNION ALL?",
         ["UNION returns more rows", "No difference", "UNION ALL is slower", "UNION ALL keeps duplicates, UNION removes them"], 3,
         "UNION ALL keeps all rows including duplicates; UNION deduplicates."),
    _mcq("sm-3", "What does INTERSECT return?",
         ["Only rows that appear in both result sets", "Rows unique to the first query", "Cartesian product", "All rows from both queries"], 0,
         "INTERSECT returns only rows common to both queries."),
    _mcq("sm-4", "What does EXCEPT (or MINUS) return?",
         ["Rows in the first query but not in the second", "Difference of values", "Rows in both queries", "All rows"], 0,
         "EXCEPT returns rows from the first query that are not in the second query."),
    _mcq("sm-5", "What is required for UNION to work?",
         ["Same table names", "Same WHERE clause", "Same number of columns with compatible types", "Same ORDER BY"], 2,
         "All SELECT statements in a UNION must have the same number of columns with compatible types."),
    _mcq("sm-6", "What is a scalar subquery?",
         ["Same as a CTE", "Returns multiple rows", "Returns exactly one value (one row, one column)", "A correlated subquery"], 2,
         "A scalar subquery returns a single value and can be used anywhere an expression is expected."),
    _mcq("sm-7", "What is a correlated subquery?",
         ["A subquery with UNION", "A subquery that runs once", "A subquery that references the outer query's columns", "Same as JOIN"], 2,
         "A correlated subquery references columns from the outer query, executing once per outer row."),
    _mcq("sm-8", "Which is generally faster: IN with subquery or EXISTS?",
         ["EXISTS for large outer tables with selective subquery", "Neither is fast", "IN is always faster", "They are always equal"], 0,
         "EXISTS can short-circuit; performance depends on data distribution and indexing."),
    _mcq("sm-9", "Can a subquery be used in the FROM clause?",
         ["No", "Only with UNION", "Only in PostgreSQL", "Yes, as a derived table / inline view"], 3,
         "Subqueries in FROM create derived tables (also called inline views)."),
    _mcq("sm-10", "What does ANY/SOME do with a subquery?",
         ["Returns TRUE if any value in the subquery satisfies the condition", "Same as IN", "Counts matches", "Checks if all values match"], 0,
         "ANY returns TRUE if the comparison is true for at least one subquery value."),
    _mcq("sm-11", "What does ALL do with a subquery?",
         ["Counts all rows", "Error", "Returns TRUE only if ALL subquery values satisfy the condition", "Same as ANY"], 2,
         "ALL requires the condition to be true for every value returned by the subquery."),
    _mcq("sm-12", "Can you ORDER BY a UNION result?",
         ["Only with UNION ALL", "Only by column index", "Yes, place ORDER BY after the last SELECT", "No"], 2,
         "ORDER BY applies to the entire UNION result and goes after the final SELECT."),
    _mcq("sm-13", "Where can subqueries NOT be used?",
         ["GROUP BY clause", "SELECT clause", "FROM clause", "WHERE clause"], 0,
         "Subqueries cannot be used directly in the GROUP BY clause in standard SQL."),
    _mcq("sm-14", "What does WHERE price > (SELECT AVG(price) FROM products) find?",
         ["Products below average", "Products above average price", "Error", "The average price"], 1,
         "This compares each product's price against the scalar average of all products."),
    _mcq("sm-15", "What is a derived table?",
         ["A permanent table", "A view", "A temporary table", "A subquery in the FROM clause"], 3,
         "A derived table is a subquery used in the FROM clause, acting as an inline table."),
    _mcq("sm-16", "Can UNION combine more than two SELECTs?",
         ["Only with parentheses", "No, only two", "Yes, chain multiple UNIONs", "Only UNION ALL"], 2,
         "You can chain as many UNION (or UNION ALL) statements as needed."),
    _mcq("sm-17", "What does NOT IN (NULL, 1, 2) return?",
         ["Rows not equal to 1 or 2", "Error", "Same as NOT IN (1, 2)", "Always returns empty set"], 3,
         "If the list contains NULL, NOT IN returns no rows because x <> NULL is UNKNOWN."),
    _mcq("sm-18", "Which is a multi-row subquery operator?",
         ["IN", "=", "LIKE", ">"], 0,
         "IN can compare against multiple rows returned by a subquery."),
    _mcq("sm-19", "What happens if a scalar subquery returns more than one row?",
         ["Error", "Returns the first row", "Returns NULL", "Returns all rows"], 0,
         "A scalar subquery must return at most one row; otherwise it raises an error."),
    _mcq("sm-20", "What is the key advantage of EXISTS over IN?",
         ["Simpler syntax", "Faster sorting", "Handles NULLs correctly and can short-circuit", "Returns more rows"], 2,
         "EXISTS doesn't have the NULL pitfall of NOT IN and stops as soon as it finds a match."),
])

ADVANCED_MCQS = Lesson("advanced-mcq", 71, "Advanced Queries: Interview MCQs", ["MCQ", "Interview"], [], [
    _mcq("adm-1", "What is a CTE?",
         ["A type of JOIN", "A permanent table", "A Common Table Expression defined with WITH", "A stored procedure"], 2,
         "CTEs provide named temporary result sets using the WITH clause."),
    _mcq("adm-2", "What does ROW_NUMBER() do?",
         ["Assigns a unique sequential number to each row in a partition", "Counts total rows", "Generates random numbers", "Ranks with ties"], 0,
         "ROW_NUMBER assigns 1, 2, 3... without gaps or ties within each partition."),
    _mcq("adm-3", "What is the difference between RANK() and DENSE_RANK()?",
         ["No difference", "RANK leaves gaps after ties, DENSE_RANK does not", "DENSE_RANK is slower", "RANK doesn't handle ties"], 1,
         "With values 10,10,20: RANK gives 1,1,3; DENSE_RANK gives 1,1,2."),
    _mcq("adm-4", "What does PARTITION BY do in a window function?",
         ["Divides rows into partitions for separate window calculations", "Sorts rows", "Groups rows for aggregation", "Filters partitions"], 0,
         "PARTITION BY creates subsets of data; the window function operates independently on each."),
    _mcq("adm-5", "What does LAG(column, 1) return?",
         ["The previous row's value", "The current value", "NULL always", "The next row's value"], 0,
         "LAG accesses a previous row's value within the same partition."),
    _mcq("adm-6", "What does LEAD(column, 1) return?",
         ["The first value", "The last value", "The next row's value", "The previous row's value"], 2,
         "LEAD accesses a subsequent row's value within the same partition."),
    _mcq("adm-7", "Can a CTE reference itself?",
         ["Yes, that's a recursive CTE", "No, never", "Only in PostgreSQL", "Only with UNION ALL"], 0,
         "A recursive CTE references itself and must use UNION ALL with a base case and recursive step."),
    _mcq("adm-8", "What does NTILE(4) do?",
         ["Groups into quartiles alphabetically", "Returns top 4 rows", "Divides rows into 4 roughly equal buckets", "Multiplies by 4"], 2,
         "NTILE(n) distributes rows into n approximately equal-sized groups."),
    _mcq("adm-9", "What does SUM() OVER (ORDER BY date) compute?",
         ["Total sum", "Count", "Average", "Running/cumulative sum"], 3,
         "SUM with ORDER BY in the OVER clause computes a running total."),
    _mcq("adm-10", "What is the default frame for a window function with ORDER BY?",
         ["No frame", "RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW", "ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING", "ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING"], 1,
         "The default frame with ORDER BY is RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW."),
    _mcq("adm-11", "Can you use WHERE to filter window function results?",
         ["No, use a subquery or CTE to filter", "Only with HAVING", "Only ROW_NUMBER", "Yes, directly"], 0,
         "Window functions execute after WHERE; to filter by their result, wrap in a subquery."),
    _mcq("adm-12", "What is the top-N per group pattern?",
         ["GROUP BY with LIMIT", "CROSS JOIN with LIMIT", "ROW_NUMBER() PARTITION BY group ORDER BY col, then filter rn <= N", "UNION of LIMITs"], 2,
         "Assign ROW_NUMBER within each group, then filter in an outer query."),
    _mcq("adm-13", "A recursive CTE must have which two parts?",
         ["Base case (anchor) and recursive step", "CTE and subquery", "JOIN and WHERE", "SELECT and INSERT"], 0,
         "Recursive CTEs need an anchor member (base case) UNION ALL'd with the recursive member."),
    _mcq("adm-14", "What does FIRST_VALUE(col) OVER (...) return?",
         ["NULL", "The minimum", "The last value", "The first value in the window frame"], 3,
         "FIRST_VALUE returns the first value in the ordered window frame."),
    _mcq("adm-15", "Can you have multiple CTEs in one WITH clause?",
         ["No, only one", "Only two", "Yes, separate them with commas", "Only with RECURSIVE"], 2,
         "Multiple CTEs are comma-separated: WITH cte1 AS (...), cte2 AS (...) SELECT ..."),
    _mcq("adm-16", "What does ROWS BETWEEN 2 PRECEDING AND CURRENT ROW define?",
         ["All preceding rows", "A 3-row sliding window", "Only current row", "A 2-row window before and after"], 1,
         "This frame includes the current row plus the 2 rows before it (3 rows total)."),
    _mcq("adm-17", "Can a CTE be used in UPDATE or DELETE statements?",
         ["Only in PostgreSQL", "No, only SELECT", "Yes, in most modern databases", "Only with temp tables"], 2,
         "CTEs can be used with SELECT, INSERT, UPDATE, and DELETE in modern SQL."),
    _mcq("adm-18", "What does PERCENT_RANK() compute?",
         ["Relative rank as (rank-1)/(total_rows-1)", "Absolute rank", "Random percentage", "Percentile value"], 0,
         "PERCENT_RANK gives the relative position of a row as a fraction between 0 and 1."),
    _mcq("adm-19", "How do you find the moving average of the last 3 rows?",
         ["AVG(col) LIMIT 3", "AVG(col) OVER (ORDER BY date ROWS BETWEEN 2 PRECEDING AND CURRENT ROW)", "AVG(col) GROUP BY 3", "AVG(col) HAVING count = 3"], 1,
         "Use a window frame with ROWS BETWEEN 2 PRECEDING AND CURRENT ROW for a 3-row window."),
    _mcq("adm-20", "What happens if a recursive CTE has no termination condition?",
         ["Returns NULL", "Infinite loop (DB may have a recursion limit)", "Returns empty set", "Error at parse time"], 1,
         "Without a termination condition, the CTE recurses until the DB's recursion limit is hit."),
])

DDL_MCQS = Lesson("ddl-mcq", 72, "DDL & Admin: Interview MCQs", ["MCQ", "Interview"], [], [
    _mcq("dm-1", "What does DDL stand for?",
         ["Database Design Logic", "Data Deletion Language", "Dynamic Data Linking", "Data Definition Language"], 3,
         "DDL = Data Definition Language — commands that define/alter database structure."),
    _mcq("dm-2", "Which is a DDL command?",
         ["SELECT", "CREATE TABLE", "INSERT", "UPDATE"], 1,
         "CREATE TABLE defines structure; SELECT/INSERT/UPDATE are DML."),
    _mcq("dm-3", "What does DROP TABLE do?",
         ["Deletes all rows", "Truncates data", "Removes the entire table including structure", "Renames table"], 2,
         "DROP TABLE permanently removes the table and all its data."),
    _mcq("dm-4", "What is the difference between DELETE and TRUNCATE?",
         ["DELETE cannot have WHERE", "TRUNCATE is slower", "DELETE is row-by-row with WHERE support; TRUNCATE removes all rows at once", "No difference"], 2,
         "DELETE supports WHERE and logs each row; TRUNCATE is faster but removes all rows."),
    _mcq("dm-5", "What does ALTER TABLE ... ADD COLUMN do?",
         ["Removes a column", "Modifies data", "Creates a new table", "Adds a new column to an existing table"], 3,
         "ADD COLUMN extends an existing table's schema with a new column."),
    _mcq("dm-6", "What is a PRIMARY KEY?",
         ["Any column", "A unique, non-NULL identifier for each row", "A foreign reference", "An index only"], 1,
         "PRIMARY KEY uniquely identifies each row and cannot contain NULL."),
    _mcq("dm-7", "What does a FOREIGN KEY enforce?",
         ["Sorting", "Referential integrity between tables", "NOT NULL", "Uniqueness"], 1,
         "FOREIGN KEY ensures values in a column match values in another table's primary key."),
    _mcq("dm-8", "What does ON DELETE CASCADE do?",
         ["Logs deletion", "Prevents deletion", "Automatically deletes child rows when parent is deleted", "Sets to NULL"], 2,
         "CASCADE automatically deletes dependent rows when the referenced row is deleted."),
    _mcq("dm-9", "What is a CHECK constraint?",
         ["Validates data against a condition before insert/update", "Checks for NULL", "Same as UNIQUE", "A type of index"], 0,
         "CHECK ensures that values satisfy a Boolean expression (e.g., price >= 0)."),
    _mcq("dm-10", "What is a UNIQUE constraint?",
         ["Ensures all values in a column are different (allows one NULL)", "A type of JOIN", "Same as PRIMARY KEY", "An index"], 0,
         "UNIQUE prevents duplicate values; unlike PRIMARY KEY, it allows NULL (typically one)."),
    _mcq("dm-11", "What does CREATE INDEX do?",
         ["Creates a table", "Sorts the table", "Creates a data structure to speed up queries", "Creates a view"], 2,
         "An index is a data structure (like B-tree) that speeds up lookups on the indexed columns."),
    _mcq("dm-12", "What is a VIEW?",
         ["A saved SQL query that acts like a virtual table", "A temporary table", "An index", "A copy of a table"], 0,
         "A VIEW stores a query definition; when queried, it executes the underlying SQL."),
    _mcq("dm-13", "What is SQL injection?",
         ["A data type", "A type of JOIN", "Malicious SQL inserted via user input to manipulate queries", "A stored procedure"], 2,
         "SQL injection exploits unparameterized queries to execute unauthorized SQL."),
    _mcq("dm-14", "How do you prevent SQL injection?",
         ["Use DISTINCT", "Use LIKE", "Use VARCHAR", "Use parameterized queries / prepared statements"], 3,
         "Parameterized queries separate SQL logic from data, preventing injection."),
    _mcq("dm-15", "What does DEFAULT do in a column definition?",
         ["Sets a value used when no value is provided on INSERT", "Creates an index", "Makes it primary key", "Makes it NOT NULL"], 0,
         "DEFAULT provides a fallback value when INSERT doesn't specify one for that column."),
    _mcq("dm-16", "What is a composite primary key?",
         ["A foreign key", "A unique index", "A key with auto-increment", "A primary key consisting of two or more columns"], 3,
         "A composite key uses multiple columns together as the unique identifier."),
    _mcq("dm-17", "What does AUTOINCREMENT do?",
         ["Creates an index", "Sorts automatically", "Automatically generates a unique incrementing integer for each new row", "Makes column NOT NULL"], 2,
         "AUTOINCREMENT ensures the ID is always greater than any previously used value."),
    _mcq("dm-18", "What is the difference between DROP and ALTER TABLE DROP COLUMN?",
         ["DROP is faster", "DROP removes the table; ALTER TABLE DROP COLUMN removes one column", "ALTER is for data", "No difference"], 1,
         "DROP TABLE removes the entire table; ALTER TABLE DROP COLUMN removes a specific column."),
    _mcq("dm-19", "What does INSERT INTO ... SELECT do?",
         ["Creates a table", "Deletes and re-inserts", "Inserts rows into a table from another query's results", "Updates rows"], 2,
         "INSERT INTO ... SELECT copies data from one query result into an existing table."),
    _mcq("dm-20", "What is the difference between a clustered and non-clustered index?",
         ["Clustered is only for primary keys", "No difference", "Non-clustered is faster", "Clustered sorts the actual table data; non-clustered is a separate structure"], 3,
         "A clustered index determines the physical order of data; a table can have only one."),
    _mcq("dm-21", "What is the difference between DROP TABLE and TRUNCATE TABLE?",
         ["DROP removes rows only, TRUNCATE removes schema", "TRUNCATE removes all rows but keeps the table definition; DROP removes both data and structure", "They are identical commands", "TRUNCATE can remove only one column"], 1,
         "TRUNCATE clears table data while preserving the table object; DROP removes the table itself."),
])


FOREIGN_KEYS_MCQS = Lesson("foreign-keys-mcq", 67, "Foreign Keys: Interview MCQs", ["MCQ", "Interview"], [], [
    _mcq("fkm-1", "What does a FOREIGN KEY constraint enforce?",
         ["Referential integrity between tables", "Entity integrity on a single column", "Query performance optimization", "Unique values in a child table"], 0,
         "FOREIGN KEY enforces referential integrity, ensuring values in a column match those in a parent table's primary key or unique column."),
    _mcq("fkm-2", "What happens by default if you try to delete a parent row referenced by a child row (under RESTRICT)?",
         ["The parent row is deleted and child rows become NULL", "The deletion is blocked/prevented", "All referencing child rows are deleted", "The child rows are deleted first"], 1,
         "RESTRICT prevents the deletion of a parent row if there are any referencing child rows."),
    _mcq("fkm-3", "What is the effect of the ON DELETE CASCADE option on a foreign key?",
         ["Prevents deletion of parent rows", "Automatically sets child columns to NULL", "Automatically deletes child rows when the parent row is deleted", "Deletes all tables in the database"], 2,
         "ON DELETE CASCADE automatically propagates parent row deletions to referencing child rows."),
    _mcq("fkm-4", "What does ON DELETE SET NULL do when a parent row is deleted?",
         ["Sets the parent row's primary key to NULL", "Deletes the child rows", "Sets the referencing foreign key columns in the child rows to NULL", "Blocks the deletion"], 2,
         "ON DELETE SET NULL sets the child row's referencing foreign key column values to NULL when the parent row is deleted."),
    _mcq("fkm-5", "Which SQL command is used to enable foreign key support in SQLite?",
         ["SET foreign_keys = ON;", "PRAGMA foreign_keys = ON;", "ALTER TABLE foreign_keys = ON;", "ENABLE FOREIGN KEYS;"], 1,
         "SQLite requires executing 'PRAGMA foreign_keys = ON;' per connection to enforce foreign key constraints."),
    _mcq("fkm-6", "Can a foreign key reference a column that is not a PRIMARY KEY?",
         ["No, it must always reference a PRIMARY KEY", "Yes, but only if it references a UNIQUE column", "Yes, it can reference any column", "No, it must reference an indexed column"], 1,
         "A foreign key must reference either a primary key or a column with a UNIQUE constraint in the parent table."),
    _mcq("fkm-7", "What happens if you try to insert a row in a child table with a foreign key value that does not exist in the parent table?",
         ["The value is inserted as NULL", "The database automatically creates the parent row", "The insertion fails with a constraint violation", "The database ignores the constraint"], 2,
         "Inserting an invalid foreign key value results in a foreign key constraint violation/error."),
    _mcq("fkm-8", "Can a column defined as a FOREIGN KEY contain NULL values?",
         ["No, it must be NOT NULL", "Yes, unless it is also defined as NOT NULL", "Only if it references a nullable primary key", "Only with ON DELETE SET NULL"], 1,
         "By default, foreign key columns can contain NULL unless they are explicitly declared NOT NULL."),
    _mcq("fkm-9", "What is a self-referential foreign key?",
         ["A foreign key that references a different database", "A foreign key that references the same table", "A primary key that acts as a foreign key", "A foreign key with no parent table"], 1,
         "A self-referential foreign key references a column (often the primary key) in the same table, commonly used for tree/hierarchical structures."),
    _mcq("fkm-10", "Which is NOT a valid ON DELETE action in standard SQL?",
         ["RESTRICT", "CASCADE", "SET DEFAULT", "DELETE ALL"], 3,
         "DELETE ALL is not a valid SQL ON DELETE action. Valid ones include RESTRICT, CASCADE, SET NULL, SET DEFAULT, and NO ACTION."),
    _mcq("fkm-11", "If a table has a composite primary key (A, B), how must a foreign key reference it?",
         ["It can reference column A only", "It must reference both columns A and B together", "It must reference a different table", "It is not possible to reference composite keys"], 1,
         "A foreign key referencing a composite key must include the same number of columns in the same order."),
    _mcq("fkm-12", "What is the difference between ON DELETE SET DEFAULT and ON DELETE SET NULL?",
         ["SET DEFAULT sets the child columns to their default values, while SET NULL sets them to NULL", "There is no difference", "SET DEFAULT is not supported in SQL", "SET NULL is faster"], 0,
         "SET DEFAULT resets the referencing column to its DEFAULT value; SET NULL resets it to NULL."),
    _mcq("fkm-13", "What is referential integrity?",
         ["Ensuring users have access permission", "Ensuring data in child tables remains consistent with parent tables", "Ensuring database backups are clean", "Ensuring queries execute fast"], 1,
         "Referential integrity ensures relationship consistency between primary/unique keys and foreign keys."),
    _mcq("fkm-14", "Why is it recommended to index foreign key columns in a child table?",
         ["To prevent insertion of NULL values", "To allow ON DELETE CASCADE to execute efficiently and speed up joins", "To enforce uniqueness in the child table", "To make the column a primary key"], 1,
         "Indexing foreign key columns prevents full-table scans on parent table updates/deletions and speeds up joins."),
    _mcq("fkm-15", "What happens if a parent row is updated and the foreign key has ON UPDATE CASCADE?",
         ["The child row's foreign key value is automatically updated to match", "The update is blocked", "The child row is deleted", "The parent row is reset to NULL"], 0,
         "ON UPDATE CASCADE updates the child row's foreign key values automatically if the parent key value is updated."),
    _mcq("fkm-16", "Which of the following is true about SQLite foreign key constraints?",
         ["They are always active by default", "They can be added to existing tables using ALTER TABLE", "They must be enabled per database connection using PRAGMA", "SQLite does not support foreign keys"], 2,
         "Foreign keys in SQLite must be explicitly enabled per-connection using PRAGMA foreign_keys = ON."),
    _mcq("fkm-17", "What is an orphan row in a database context?",
         ["A row in a parent table with no children", "A row in a child table whose foreign key references a non-existent parent row", "A row containing only NULL values", "A deleted row"], 1,
         "An orphan row is a child record referencing a non-existent parent ID (a violation of referential integrity)."),
    _mcq("fkm-18", "If ON DELETE NO ACTION is specified, what happens when a parent row is deleted?",
         ["The database does nothing and allows orphan rows", "It acts similarly to RESTRICT, blocking the deletion if referencing rows exist", "The child rows are deleted", "The child columns are set to NULL"], 1,
         "NO ACTION acts similarly to RESTRICT by checking and raising a constraint error if child records exist."),
    _mcq("fkm-19", "Can you define multiple foreign keys in a single table?",
         ["No, a table can have at most one foreign key", "Yes, a table can have multiple columns referencing different tables", "Only if the table has no primary key", "Only in composite keys"], 1,
         "Yes, a table can have multiple foreign key constraints pointing to different parent tables."),
    _mcq("fkm-20", "In a one-to-many relationship, which table contains the foreign key?",
         ["The 'one' side (parent table)", "The 'many' side (child table)", "Both tables", "Neither table"], 1,
         "The foreign key is placed in the child table (the 'many' side of the relationship)."),
])

MCQ_LESSONS_2 = [AGGREGATIONS_MCQS, SETS_MCQS, ADVANCED_MCQS, DDL_MCQS, FOREIGN_KEYS_MCQS]
